= The Toyota Production System

== The book in bullet points

* Two pillars: JIT, Autonomation
* Just in time production method
** Why?: Customers needs are highly varied and changeable. Production needs to adjust to accomodate that.
** Eliminate waste (WIP / inventories)
** Pulling WIP, not pushing it. Low inventories
** Virtuous cycle: Meeting varied customer needs requires elimination of waste. Elimination of waste drives understanding of customer needs. Understanding customer needs allows to meet them.
** Requirements: 
*** production leveling (regular flow)
*** small lot sizes
*** very short set up time
*** autonomation: BAU runs automatically. Exceptions get automatically detected and completely stop the line.
* Generating new ideas
** Question received wisdom / common sense
** Ask why 5 times
** Get on the factory floor for deep understanding
* Implementing new ideas
** People will be upset. You will have to bust heads
** Comprehension time of the idea must be near instantaneous. Simplify
** Management have to be willing to give you room to experiment. But don't expect active support.
** It takes a long time

== Questions from a second read

=== What is the Toyota Production System, what is it for and why is it necessary?

=== What are the primary goals of the TPS?

=== What is Autonomation and why is it desirable?

=== What is the Kanban systems and how does it work?

=== How does the TPS compare with the Ford system?

=== Who were Toyoda Sakichi and Toyoda Kiichiro?

=== How did the TPS change over time?

=== What are the necessary preconditions for TPS to work as intended?

== Notes from first read

=== Structure

The book has six chapters. It is a bit hard to pin down exactly what each one is about because it's not the most cleanly sub-divided book; ideas and concepts spill over and crop up all over the place. But broadly here's a good way to think about it if you don't take it too literally

* Chapter 1 *Starting from need* is about the conditions that lead to TPS.
* Chapters 2 *Evolution of the TPS* and 3 *Further Developments* (which seem to me to be the key ones) focus on the implementation of TPS, but also on some of the ideas about arriving at and implementing ideas in general.
* Chapter 4 The *Genealogy of TPS* is about how Toyota was formed, and in particular how the genius, ideas and attitudes of Toyoda Sakichi and Toyoda Kiichiro paved the way for the TPS.
* Chapter 5 *The True Intention of the Ford System* is a comparison of the Toyota’s small batch, Just-in-time system to the Ford’s large batch system. It is about how, though they are in many ways complete opposite in implementation, there are similar attitudes underpinning them. 
* The short Chapter 6 *Surviving the low-growth period* is about the current (i.e. late 70s) economic climate of low-growth. Many ideas are the same as in the first chapter.

=== Summary of themes

In Taiichi Ohno's short preface he describes the market changes that necessitated the TPS: namely, customer needs required the production of small batches of variable products which the customer 'pulls' from the market as needed, rather than the mass production of homogeneous components which are 'pushed' onto the market. This made the old 'Ford' system of mass production, which was geared to the latter world, very wasteful. TPS is about finding and reducing waste, so producers can survive in this environment.

Ohno sees the core interconnectedness of this trifecta of focusing on individual customers, who have small and varied needs, which requires a focus on elimination of waste. He finds that this elimination of waste inevitably requires and results in a clearer picture of the individual customer.

----
      Meeting Customer
       /  Needs   \
      /            \
     /              \
Elimination _____ Understanding
of waste          Customer needs
----

Aside from the 'machiney' parts of eliminating waste, other themes are challenging received wisdom, constant questioning and encouraging teamwork.

=== Terms

* *Automation and Autonomation*: Automation is a machine that does everything without a human; Autonomation is when a machine can detect defects, and stops when a defect is detected for a human to intervene, but otherwise can run unsupervised.
* *Ford system*: Mass production, the assembly line, large batches minimize machine-setup time, bring the car to the inventory not the inventory to the car.
* *Just-in-time*: Eliminate inventory because inventory is waste. Components should be available when they are required and not before.
* *Kanban*: Tag, card. In the TPS it’s a printed sheet in a clear plastic folder which has on it (among other things) the number of parts needed, a ‘shopping list’ that a later process passes to an earlier one to withdraw components it needs. A Kanban must be attached to any and all components in the factory.
* *Wastes*: Inventory is the big one. Defects are another. Moving (i.e. moving components between workstations) is a 3rd. These are non-value add work. There is another kind, which is ‘headless chicken’ movement, which is just people doing things that are not inefficient processes, but result from people not knowing what they are doing, i.e. lack of standardization, formality and clarity.
* *Production Leveling*: JIT breaks down if flow in the factory is ‘lumpy’, i.e. if the later process is quiet most of the week but suddenly requests a massive amount of components. So the production must be ‘levelled’ and made consistent throughout the day and week, i.e. the flow of requests from later processes must be managed so there are no hills and valleys.

=== Summary of the book after the superficial read

==== What is the book about and what does it say?

The Toyota Production System (TPS) is the authors method of effectively running a (car) factory in a time of low growth, by relentlessly eliminating waste, primarily inventory, but also other wastes.

This is achieved first by focusing on a 'just-in-time' system of production, whereby the later process pulls from the earlier process the components it needs, and the earlier process produces only enough components to satisfy the later process, thereby eliminating inventory and the associated costs. This is enforced by the 'kanban' system of order sheets. A consequence of this is that lot sizes need to be small, and the time necessary to set up a machine to make a different component must be very, very short.

A necessary precondition to this is 'production leveling', where components are required by later process at a steady and reliable pace (a 'flow'), not in big chunks.

The second requirement is 'autonomation', or automation with a human touch, where machines themselves have mechanisms built in where they stop themselves (or refuse to work) if they detect a defective part, preventing the creation of defective parts. This means a machine doesn't need to be monitored all the time, and allows reduction of manpower.

Aside from the concrete implementation of the TPS, the book is also about the method of thought by which one can come up with new ideas, and not be bound by received wisdom - in Ohno's world, the Ford system of mass production which ruled car manufacture methods, and to a lesser extent accounting measures. By questioning deeply ('asking why 5 times') and observing the whole carefully from the factory floor without getting distracted by the detail, we can achieve a 'revolution of consciousness' allowing us see through the accepted 'common sense' and come to deeply understand our working methods, and from them logically derive new and better ideas. In this, Ohno is inspired by the genius of Toyoda Sakichi, inventor and the founder of Toyoda.

He also has much to say in general about implementation of methods. You will have to bust some heads, people are not going to like your changes. Proper processes can't be written from a desk, they have to written on the factory floor, with the workers, and they must be tried and revised many times. If a process can't be understood on sight, you need to simplify it. Management need to be willing to give you some rope to experiment and willing to put up with some complaints (it is unlikely management will be actively supportive, so don’t expect them to be). It will take a long time.

==== Why did the author write it?

He designed the TPS and strongly believes it is the best way to produce things in a low growth environment, and less strongly in general, and he would like to share that with the world, and have other companies use it. He is not very explicit about why, though at one point he does quote Henry Ford admiringly about the purpose of making work more efficient, which is to provide people with lower-cost high-quality products which enable them to enhance their quality of life. Maybe he just loves the puzzle of it though, he strikes me more of that type.

==== What is the main takeaway the author wants to leave you with?

That the TPS is the best way to run a factory in a low growth environment, and that it is necessary to look 'upside down' at things to generate new ideas.

==== Will you read the book more thoroughly? Why or why not?

Yes. It is a weirdly organized book, and hard to pin down the thought behind the ordering of the ideas, but the ideas themselves are very provocative. I found it hard to get through a couple of pages without reading something which sent me off on a tangent about how to re-contextualize what was said to my own situation. While the TPS ideas are very much focused on the factory (for example inventory is the primary focus), there is much even there which can be re-purposed for the knowledge work which we do - in particular the emphasis on detecting defects early by having gates in place which automatically prevent them being passed on is especially critical and actionable in our world. On the more abstract concepts of idea generation and process implementation, nearly all of that is very directly applicable and there is much to learn from them.

=== The 6 rules of kanban

. The later process pulls from the earlier one
. The earlier process only produces the amount pulled by the later process
. You can't pick up or produce components without a kanban (a work order sheet)
. A kanban must be attached to any and all components
. Defective products never get sent on to the next process.
. Reduce the number of kanban

== Implications for 'process like' knowledge work: Trade booking

TPS came about because there is a customer at the end of the process, whose needs are varied across customers and changeable over time. TPS aims to respond to these needs.

Can this be compared to one of our operational processes, e.g. the trade booking process?

I think at best it needs significant changes.

For a start, the 'supplier' in the trade booking process is the trader. It is not for ops to 'pull' trades as they need them. The flow of trades will happen regardless of the needs of ops. It is for ops to handle them as they come in. It is, by nature, a 'push' operation, not a pull. Said another way, the amount of WIP is not in the control of the people implementing the process.

Can there be said to be a 'customer with varied and changeable needs' in the trade booking process? I don't know that there can. Who uses the information that Ops are booking? There's the analytic use case, which will generally want information about the trade at start of play on the day following the trade date. There are the operational use cases, such as Accounting. But I don't think their needs can be called diverse and changeable. To the contrary, both of these customers want things to be as consistent and repeatable as possible.

The ideas of Six Sigma are, I think, a closer fit to how these processes should be working. Decreasing variability, optimizing throughput of the _system as a whole_ are goals. Meeting diverse needs in an effective way is not.

== Implications of the TPS on a Production Issue management function

The customers here are quite clearly the business users who are having some problem with a system (A wrinkle: they might not _know_ they have placed an order, if the ticket comes from a system.).

The customers needs can certainly be said to be variable: Each system has unique types of failure.

What are the raw materials and how are they sucessively transformed into WIP?

== Long notes second read

=== C1 sharting from need

* Oil crisis '73 sparked interest in what Toyota were doing
* End of rapid growth

== Questions for book club

* What are the big ideas here?
** minimize inventory
** autonomation
* What were the key ideas that resonated with you?
* TO talks about a 'need' that drove the success of JIT. What were the conditions that made JIT sucessful?
** Low growth
** Complex production flow, thousands of parts
** Non-homogenous customer demand
* Inventory / avoiding overproduction is a big thing in TPS. What is the equivalent idea in a service industry? Is it as critical as it is in the production world?
* In a production system, the things flowing through the production line are physical parts. What flows through the Varde production line? What are some examples?
* What are examples of Varde's production line?
* Pull vs. Push: are there any examples of this in the context of Varde's production processes?
* TPS has a Kanban, or sign board, signalling that materials are required. What are the signals we could use to indicate a need for 'materials'?
* What are the implications of the TPS for 'supervisor' processes. That is, the need to plan overall coordination? Does it need more centralized coordination or less?
* TPS talks about Autonomation. What would that concept imply in the context of a Varde business process?
* What would prevent the implementation of an autonomous process?
** e.g payments: need someone to approve
* What is the role of a manager or supervisor in a TPS?
** baseball team manager
** Special instruction in case of abnormality
* TO talks about 'visual control' or 'management by sight'. Obviously in the context of a factory floor, the implications are clear. What are the implications for a information based process?
* TO talks about resistance to change. How did he overcome this resistance? What lessons canwe take from that?
* What was the attitude of management to the changes that TO was making? 
** Page 31
* What are the key requirements for establishing a production flow?
* The wastes: how do these translate to Varde business processes?
** Overproduction
** Waiting
** Transportation
** Processing waste
** Inventory
** Movement
** Defects
* 'The parts should be handed over as if they were batons'
* TPS emphasises that defective work should not be accepted. What does 'defective work' mean in the context of an information business? How do our business processes handle defective work now? What would they look like if the downstream team refused to accept defective work?
* P45: Installing an 'autonomous nervous system'. 'making judgements autonomously at the lowest level'. This requires independence of decision making, without management, without cross team collaberation. Are we set up to implement things like that? What permits or prevents that in a production environment? What permits or prevents that in our environment?
* P46: '...so that change will not be felt as change'. How do you structure technology and process so that you can make changes that are not felt as changes?
* P47: Excess information must be suppressed. Provide only information that is needed. Anything else is uneconomical. Is this something we do here? Can it be?
* P53: 'All considerations and improvement ideas...must be tied to cost reduction'. 'without proper study, we can easily end up with an improvement that, while making a small cost reduction, costs too much to implement'. Very relevant for technology. Dev costs are very high, run rates at 100k per month. What do we get from that?
* P57: Non-value added work. Moving data around. Unnecessary clicks of buttons.
* What is 'value added work' in a typical information business process?
** enriching or enhancing information.
* P59: What is hidden waste in our context? How can we make that hidden waste visible?
* P63: Take good care of old equipment. For us this is our technology. 'Depreciation' and 'Book value' is artificial. "It shows we want new machines because we don't have a better idea".

== Quotes

> Abnormalities will never disappearif a worker always attends to a machine and stands in for it when an abnormality does occur. ... If materials or machines are repaired without the managing supervisor being made aware of it, improvement will never be achieved and costs will never be reduced
Page 7
