= Data and Reality

== Preface
p28: Data is to information:

* what grammars are to language
* what what formal logic is to the way we actually think
* what the map is to the territory

That is, it's an artificial formalism

p29: Information is, in the limited sense, that which is stored, maintained in quantity, with a simplistic structure/format. We focus on describing the information content of a system.

== Chapter1: Entities
p35: We expect correspondence between a 'thing' in the real world and a 'representative' in our information system. Ideally 1:1 but often not. But what is a thing in the real world?

A 'Thing' is some physical object or idea that exists in the real world that we want to name and reference. A 'Representative' is the information construct in the information system corresponding to a thing.

p36: When we loosely refer to a 'Thing' we could be using the word in 2 senses. The first is in reference to an instance of the 'Kind' Thing, the second is in reference to the tking of Thing itself. e.g. when we refer to a 'widget' we could be talking about a physical widget that you hold in your hand, or about the idea of a widget.

p38: Sameness could be:
. how many kinds of thing is this thing?
. You have a thing and I have a thing. Are we talking about the same thing? Am I pointing to the brick where you are pointing to the wall?

p39: A book could be
. A specific physical thing, (you tore the cover of my book!)
. The idea of the book (I've written a book)
. A collection of volumes (I've just finished vol.1 of the book War and Peace, now I need to go to the library to check out Vol.2)

p41: The classification problem is about unambiguously communicating a concept using the ambiguous medium of language. This makes it hard to assign a word to one 'thing' because, consumed in another context, it might be taken to represent some other thing.

p46: There is not natural set of categories. The world is always fuzzy. Any categorisation model we come up with is artificial.

p49: A piece of information about a thing can often be represented either as a categorization, an attribute or a relationship, basically arbitrarily. e.g. a person could:
* be a member of the category 'parents'
* have the property 'has children'
* have the relationship 'parent of' with another person

p49: A thing can have an essence (what category it should be put in) and it can have different uses of purposes (its roles). Roles tend to be context dependent - think of all the purposes of a metal rod - so trying to use a role as a category will make things difficult.

p53: We are not modelling reality, but the way information about reality is processed by people.

== Chapter2: The nature of an information system

p58: Categories are useful because you can specify rules and constraints that apply to any individual belonging to that group.

p59: An integrated database is sort of like the system's analogy of the real world: an ongoing, persistent thing that an application can query in general, for use in its own specific context. But efforts to model the whole organization in general, with the aim of meeting all potential contexts, are doomed to failure.

p64: A thing in the real world has a representtive in the system. As we saw, such a representative could actually be spreda across multiple records, with different views or perspectives. We could sometimes integrate these records into a single "pool" that can be used more generally. But recognize that a record could include facts relevant to more than one pool - you can't cleanly separate.

p66: the properties of a representative:
. 1:1 correspondence with a thing in the real world (even if spread across >1 records)
. Can be linked together by relationships, names and types
. Constrained/Specified by types, tests, invariants
. Not omniscient - they are perceivers, they only know what they have seen.

== Chapter3: Naming
p76: Qualification of a name is the addition of terms which narrow the scope of possible reference, to resolve potential ambiguities in the name itself. Thus "Harry" can be qualified as "Harry from the office". This particular form, qualification by relationship, is common.

== Chapter4: Relationships
p88: A kind of relationship can be thought of as a named tuple, where the name is the statement, reason, or verb. For each cell there can be a role name, specifying the role in the realtionship, and the element itself will be category, or categories, comprising a domain. The 'degree' of the relationship is the number of cells in the tuple. An instance of the relationship type puts instances in place of the domains.

`WorksFor(Employee, Department)`
`WorksFor(bob, accounting)`

== Chapter5: Attributes
p99: There is no fundemental, objective distinction between and attibuted, a realtionship, and a category. Anything can be modelled as any one. How we would model it would be dependent on context, and ultimately based on intuition.

== Chapter6: Grouping, types, categories, sets
p109: Two ideas of grouping are often combined: Grouping things by "what they are", and expressing about a thing its attributes, relationships and names.

p110: The problem with using types to divide things into groups is that it assumes certain things which when brought into the real world often fall down. The big one is exclusivity. Or at least non-overlapping hierarchies. Grouping using sets based on predicates eliminates most of these problems - though it does bring in some new ones.

== Chapter7: Models
p119: A model (that is, a technique for representing information) is not "One way". A model shapes our view of reality and limits how we perceive it. A model is a lens, and it can distort as well as reveal.

== Chapter8: Records
== Chapter9: Philosophy
