= The Economist: Summary of the May 22nd edition

== Leaders

=== Race in America

Flloyd's death prompted the biggest civil rights protest in American history. Chauvin was convicted of murder.

What needs to change?

Despite gains in legal and political rights, measures of relative poverty and segregation haven't moved in 50 years.

Three causes:

* secular economic trends
* aftershocks of slavery and segregation
* present day bigotry and racism

The first two are the biggest causes, but the last gets most attention. Covid-19 has killed blacks disproportionately, but it's unlikely that racist doctors are to blame. Due to past racism and present poverty, blacks are more likely to suffer from pre-existing conditions, and less safe work environments, less likely to have health insurance.

==== Poverty Policy

Rooting out entrenched racist views is largely not in the power of government. Poverty and structural racism are.

Biden's new child tax credit expects to reduce child poverty by 40%, and halve the number of poor black children.

This colorblind legislation is preferable to racially targetted ones. First, it is more likely to get broad backing from the public. Second, helping all poor Americans is beneficial in general, and helps blacks disproportionately. The ACA has reduced the number of uninsured African Americans by 40%.

Policies aimed generally at poverty are morally preferable: Not all blacks need help. Other minorities with similar conditions will also be helped: Latino, Native American, Asian.

==== Police reform

There have been advances in the last year. "Qualified Immunity" has been trimmed in many places. While presented as a racial issue, police killings of all unarmed men is higher than it should be. Separating unjustified killings should be seen as a nation priority, and a civil rights issue affecting all Americans.

==== Organizations

Companies and Universities should pay more attention to race when hiring. But, where practical, a race-neutral approach would be better for America, and especially its African American citizens.

==== The Future

In the next 50 years the US will become the first big, rich country where no single racial, ethnic or religious group will be in the majority. If politicians exploit the tribal fears this raises, the transition will be turbulent.

=== Job vacancies in the rich world

As they come out of the pandemic, businesses are shouting about labor shortages. But unemployment is high and not dropping. Why the mismatch?

Some see this as good. Companies are boosting wages to attract workers. Pay growth is a strong 3% in the US. Qualification requirements are being dropped.

There is a downside: a bidding war for workers could cause an inflationary spiral. A labour shortage means products that are wanted won't get produced. Having people sitting idle is a waste of talent. 

Governments should consider:

* Payments
* Passports
* Patience

Business people are convinced that unemployment insurance and benefits are the cause of the shortage. The evidence for this is slim. Australia has ditched its payouts, and still has the same problem - in fact shortages have worsened. UI should be redesigned to encourage work. Making one-off payments to people who find work, for example, has had good results in past recessions.

Immigration has been slashed during the pandemic. This is a price-tag that must be accepted or reversed.

Finally, just waiting for more people to get comfortable with going to work should show results.

=== Italy might get a hard right government

In February, Draghi became PM. Italian debt yields has only a 1.2pp premium on Germany's, his government has a large majority in parliament, and the EC is about to give him a huge amount in C19 recovery funds.

However, Italian politics is unpredictable. Populists are seizing on an increase in boat migrants. Salvini's Northern League, still the most popular party in the country, is losing ground to an even more radical outfit, the Brothers of Italy (FdI), which has roots in the Fascist movement. The FdI has overtaken Letta's Democrats, the main center-left party.

The FdI, League and Berlusconi could probably get enough votes to form a coalition government.

Throughout Europe, having the hard-right in power is becoming less unthinkable. Le Pen is neck and neck with Macron. Spain's Peoples Party is seeking a deal with Vox in the Madrid region.

=== Sustainable Finance is a mess

The private sector has a hard-on for green investing. Green firms, like solar panel firms and hydrogen fuel producers, have seen share prices rocket, with 6 doing better than Tesla since the start of 2019. Big companies boast about their green credentials. Assets Managers are selling ESG products - inflows for these are a quarter of the total, up from a tenth in 2018.

ESG funds suffer from Greenwashing. The 20 biggest ESG funds hold 17 fossil fuel producers on average, including Exxon and Saudi Aramco. Gambling, alcohol and tobacco holdings are also common. The SEC worries that investors are being mislead.

The EU's Green Deal includes rules about sustainable finance, telling investors what is green and what isn't. This has been subject to political forces, with countries lobbying to have nationally important industries, including natural gas, included.

Instead, investors should decide for themselves what is green. But to make this practical, better disclosure is needed. Current reporting is largely voluntary, and full of holes. Obscurantist puffery is common. A manager should be able to figure out the carbon footprint of their holdings, but this is not disclosed rigorously, and how to aggregate results is unclear. There should clear an mandatory guidelines for this disclosure. 

=== Eritrea on the march

Ethiopia's prime minister, Abiy Ahmed, and Eritrea's president, Issaias Afwerki, are partners in a bloody war in Tigray.

The two countries were formerly at war. Abiy won a nobel peace prize for brokering a peace in 2019. He was seen as a force for liberalization and democracy. Issaias is an aging and violent dictator. The peace seemed to bode well for Eritrea also. Sanctions were lifted, cash poured in.

Things have soured since. Encouraged by promises of support from Issaias, Abiy attacked Tigray, in what has now devolved into a bloody stalemate. War crimes against civilians by Eritrean and Ethiopian troops in Tigray are common. Food and farming supplies to the region have been cut off. Issaias is the winner from this. His troops are deep in Ethiopian territory, including along its border with Sudan, which Eritrea has a separate beef with.

Issaias seems to be encouraging despotic behaviour in Ethiopia, and also in Somalia, encouraging the president there to overstay his term limit.

The West is slowly cancelling the recent opening up to Eritrea, though few hold out hope that it will have much impact: the country is used to isolation. Pressure on Abiy may be more successful though. 

== USA

=== The American Welfare State

Biden is proposing an ambitious European-style expansion of the safety-net, the American Families Plan, at a cost of $1.8trn. It includes

* Child allowance
* Paid family leave
* universal pre-school
* subsidized child care
* free community college

This reflects a shift in the Democratic party over the last 20 years. Clinton-era democrats were largely on-board with Reaganite ideas of limited government assistance. These days they are not. Several factors are contributing to the shift:

* general worries about inequality
* changes in the views of economists
* a leftward shift in the party
* GOP abandonment of fiscal responsibility in the Trump era.
* recent spending splurges following C19

Polls show broad support from Republicans on pre-school, clean energy research, and child allowance (though not on a public option for health insurance).

Poverty reduction has tepid support across the board. What is popular are programs aimed at the middle class, which the poor also benefit from.

the AFP is a good plan, but could use some trimming.

One in six American children live in poverty, among the highest in the rich world. Support for young people is flimsy (the elderly get Social Security and Medicare). Child allowance is the main anti-child-poverty tool in rich countries, and America doesn't have one. The AFP would extend a recent C19-bill payment plan ($3k pa per child) beyond its 1 year duration, to 2025. This is expected to halve child poverty.

The paid family leave allowance, almost universal in the rich world, would guarantee 12 weeks of paid maternity leave, costing $225bn over the next 10 years. Improvements in infant health and maternal health from this are well demonstrated outside of the US and within in, in state programs such as California's.

Universal pre-school for 3-4 year olds has a bill of $200bn. Small scale pre-school initiatives have impressive results, though it remains to be seen how well it scales.

Other parts of the AFP are more questionable. Child care is already incredibly expensive in the US. The white house believes subsidies would improve this, but it is also possible it will merely push up prices and reduce quality of care. A study of Quebec's program of subsidised child care found that child behaviour was worsened, and parents were less caring and had worse health.

The far left of the Dems has much more radical aspirations, including cancellation of student debt and regressive subsidies of college courses which are mostly attended by the rich. Nonetheless, this is the biggest social policy experiment since the 60s.

=== Silicon valley and politics

Most people try to keep work and politics separate. Techland is different. Internal forums debate politics and social issues. Some firms, including Facebook, Google and Shopify, are pushing back. Basecamp caused a stir (and lost a lot of employees) by declaring itself 'politics free'

Silicon valley had roots in the counterculture of the 60's, and tech shifts often intersect with social issues - the FOSS movement for example. More recently, employees have started expecting workplaces that align with their personal values.

The pendulum is swinging back. Slack is not a great place to put across nuanced views. Moderators have had to be put in place. Workers are vocal and management are defensive.

A recent poll suggests two-thirds of adults want to be able to discuss racial-justice issues at work.

=== Children divorcing parents

Estrangement between family members is common in America. A recent survey found 27% of adults are estranged from a close family member - though it is thought that this under-reports the true number because of the shame of admitting it. There isn't much historical research on it, so it's not clear what the trend is

The most common estrangement is between parent and child, usually with the child initiating it.

A rise in individualism emphasising personal happiness, displacing filial duty is the biggest factor. This is emphasised in America, which is more individualistic than most rich countries, has a commensurately higher divorce rate, as well as a fair amount of inter-state mobility.

The consequences of estrangement are, first, that it tends to perpetuate within families. It likely exacerbates loneliness in old age.

=== CDC guidance and America's vaccination rate

The CDC this week rolled back mask requirements for vaccinated Americans. Possibly this was an incentive to get vaccinated. But vaccination rates are slowing despite an ample supply.

Possibly the announcement is a reaction to criticism by public health officials of previous overcaution by the CDC.

The announcement was criticized as being out-of-bounds of the CDCs responsibility. The CDC is supposed to provide scientific advice, not announce policy.

Probably it will act as a _disincentive_ for vaccination. Minnesota was encouraged enough to remove all mask requirements (except for child-care and schools), regardless of vaccination status. Many states are following th guidance to remove mask requirements for vaccinated people without procedures for checking vaccination status, effectively removing all mask requirements. 

=== Philadelphia police 1985 house bombing

In 1985, the Philly police were involved in a shootout with a black cult, MOVE, in a house. In the end, they dropped explosives on it from a helicopter, knowing there were children inside. 60 houses were destroyed in the resulting fire, 250 were left homeless. 11 people died, 5 children. The fire department were ordered to let the fire burn.

=== Lexington: Biden and the Middle East

Despite opposite policies, America's results in the Middle East have been largely the same under Obama and Trump. Both tried and failed to scale back commitments in the region. Biden will try the same thing.

The violence in Palestine this week is a test of that resolve.

Despite being a rare Democratic Zionist, Biden will not be ditching the Palestinians. He restored $250m in aid that Trump but. He has promised to reopen the consulate in Jerusalem that Trump closed. But he views the peace cause as a losing one under the current leadership of both sides, and says he won't be spending much time on it.

The administration was slow to respond to events. Its strategy is supportive of the status quo, resisting calls from the left to pressure Israel. It has not called for a ceasefire, or allowed the UNSC to do so.

The administration is going the quiet diplomacy route. It believes Obama's attitude to Netanyahu was counterproductive. Instead it hopes to gain leverage on him by providing early support which it can later threaten to withdraw. It hopes that growing antipathy to his cause on the left will provide further leverage.

The administration does have ambitions to restore the Iran nuclear agreement, which affects its ME moves. All powers in the region will be looking to Biden's reaction as an indicator willingness to stand by its allies.

== Britain

=== Consumer spending

Restaurants are starting to open. Pubs are doing excellent trade. The economy is recovering quickly.Inflation rose from 0.7% in March to 1.5% in May.

Too quickly? Risk of overheating? Premature. Most of the rise is due to global energy costs.

Wage growth was 4.6% in Q3, but the ONS says this is likely a falloff in low-paid jobs. A true rate is more like 3%.

Household balance sheets are healthy. Savings as % of disposable income spiked to 25% in 2020, from a long term average of 10%.

Whether or not people start to spend that money will impact how quickly the economy will recover. Consumer confidence measures point to a rebound in spending.

=== DUP and UUP leadership

The UUP also has a new leader: Doug Beattie. A former soldier in Afghan, working class, secular.

The DUP overtook the Ulster Unionist Party (UUP) as the dominant party in NI 20 years ago. It pragmatically agreed to govern with Sinn Fein, an ideological rival. 

But in recent years it has become scandal prone. Edwin Poots this week took over from Arlene Foster as leader. He is a Brexiteer, a fundamentalist and a creationist. His deputy will be Paula Bradley, the most liberal top DUP member. Both are keen on reforming the party.

Poots has some difficult road ahead. The Irish Sea border for example. He hopes unionists will win a majority in Stormont next year and vote it down. This looks unlikely at this point. The DUP is losing support to other Union parties. 

It's possible Sinn Fein will be largest party in NI. Unionism took 50% of the vote in 1997. By 2019 it was 43%. Calls for Irish union referendum are growing.

=== Farmland prices

East Anglia has the best farmland in Britain. In the 19th C the fens had been drained, leaving rich soil behind.

But farmland is more expensive in less productive areas, especially since a slump in after Brexit, when the EUs generous farm subsidies were off the table. In the Cotswolds, where farmland is generally hilly and lower quality, land has retained its value.

Mostly this is driven by 'lifestyle buyers', to whom the farmhouse and the view are the important thing (contract farmers do the actual farming). The Cotswolds have  less scene-spoiling things like motorways and electricity pylons than in East Anglia.

=== The C19 inquiry

Johnson announced a public inquiry into the government response to C19 on 12th May. It can compel documents and question witnesses under oath. It will be one of the most complex public inquiries, massive in scope, comparable to the Butler and Chilcot ones on Iraq. 

Judges are often tapped to run them. They are good at the investigation part, but less so at the 'designing policy' bit. And in this case you have the science dimension too.

=== C19: The Indian variant

B.1.617.2 or the "Indian Variant" of C19 is believe to be more infectious than the "Kent variant" (B.1.177) that drove Britain's second wave of infection, and which until recently was responsible for nearly all cases.

The environment is different though: most Britons have received a first dose of vaccine, and a good number have had two. The spread pattern will likely be different.

New cases are mostly being found in teenagers - few old people are getting it. Despite the new strain, overall infection, hospitalization and death numbers are flat.

What if the numbers go up? The health services will struggle to cope. A long backlog of patients for other conditions has built up, and morale is low. The government would come under pressure to roll back its easing of lockdown measures.

Cases of 617.2 are greater in areas with low vaccine rates - which are poor and ethnically diverse areas. The best action is get more jabs in arms.

=== The Kensington Olympia Theatre

The Olympia in Kensington is due to open in 2025. It will have 1.5k seats.

=== Class makeup of the Civil Service

In 68, the civil service was dominated by Oxbridge generalists. The Wilson government wanted to have people with specialized technical skills, to encourage science-fuelled meritocracy. Around 66% of the senior civil service were from a "high socioeconomic background". According to a report published on 20th May,today it's 72%. Working class backgrounds have gone from 19-18%. (Comparisons are tricky - less of country is proportionally working class now than in 68.) 

The report proposes targets to improve class representation, as has been done with some success for women and ethnic minorities.

=== China

==== A revival of Confucian education

growing nationwide demand for _guoxue_ - national studies. Classical Chinese thought, texts, morals, especially Confucian ones. Behaviour: bowing, greeting, sitting. Traditional dying techniques and calligraphy, tea and chess. But building character is the main goal.

Confucius was vilified during the 20th C, in the belief that it was blocking progress.

Driven in part by a sense of cultural loss. Rediscovering heritage. But it also now meshes with official objectives. Respect for authority, deference to elders. Emperors used it to instil obedience. Xi wants that. It is also intrinsically Chinese, so plays well with increasing nationalism and growing cultural self-confidence.

Others see Confucian morals as salves for modern social problems. They encourage calm and focus in children.

It's also a reaction to the national obsession with exams. Guoxue is a way to distinguish children in the rat race, and to shield them from relentless competition early on.

==== Adopting poor graduates

Traditionally male preference in Chinese families. Girls were married off and left the family. Girl babies were often killed. A male heir was needed. There was another way for rich, male-less families: recruit a poor man as a live-in son-in-law. The man agreed to take the wifes name and take care of his parents-in-law in preference to his own parents. This was banned between the 13th and 17th C. The practice was subject to social scorn.

Modern China is more pragmatic. A new national census shows that China is aging fast, and has one of the lowest fertility rates in the world. The population will soon be shrinking. The effects of the since-revoked one child policy will endure. 111 boys are born for every 100 girls.

Optimistically, this shortage will empower women. As an increasingly urban country, that might help too, as will better education (women outnumber men on campuses) and increased wealth.

An old tradition, the _zhuixu_, or matchmaking, comes into play. Some specialize in finding poor graduates for property owning women.

== Europe

=== Balkan money laundering through property

Dirty money is being laundered through property throughout the Balkans, driving up prices despite the pandemic. Towers are rising in Tirana, Pristina and Belgrade. In Tirana prices have doubled since 2017. Cocaine trafficking, which has boomed in the last few years, is a prime cause of the new dirty money. The countries have sound AML laws, but enforcement is patchy. Officials want to crack down, but also like the jobs and investment.

=== NATO soldiers phones

Enemy forces can use cell phones signals to direct artillery fire. They give away your position. A ban would hurt recruitment and morale.

Propaganda can be sent with pinpoint accuracy to mobiles - "psyops texts" - "who is robbing your family while you are paid pennies waiting for your bullet?", or  messages to family members falsely announcing infidelity or injury.

* data can be captured remotely from mobiles
* soldiers can be fooled into tapping links that download spyware
* legit apps can contain malicious code
* telecoms employees can be bribed or blackmailed into providing access
* voices can be 'cloned' to pass fake orders (NATO doesn't pass orders by mobile, but local militias do)

=== Germany will apologize for the Herero and Nama genocide in Namibia

Took place 1904-08. Al least 75,000 died, including in labour camps.

In 2015 Namibia and the German government started negotiations on acknowledgement and compensation. They have been bitter, mostly over money. On 15th May agreement was reached, subject to consent of parliaments.

There is concern over inviting other claims from Africa, and from European nations. The idea is, the 1948 Genocide Convention can't be applied retroactively, and any money is not "reparations", but a voluntary morally-motivated extension of development aid.

There are divisions within Namibia too. It's the Ovambo ethnic group that is dominant in Namibia, and Herero and Nama people feel shut out of the negotiations.

=== A PiS spending splurge in Poland

PiS is well aware that handouts win votes. They were a big part of their 2019 election campaign.

On May 15th PiS announced it's "Polish Deal" - a policy package of health care, taxes, pensions, housing and state investment.

PiS combines social conservatism with left-wing economics. The 500 zloty per child handout of 2016 and several minimum wage increases.

* Health spending will rise from 5% to 7% - the EU average - by 2027
* the minimum taxable income threshold will rise from 8k zloty to 30k, and the upper band will be raised too.
* new parents will be 12k per child after the first

Unemployment is 6.4%, but 8% in the rural east, which is PiS's base. The economy is set to grow 4% (2021) and 5.4% (2022) even before these measures. But inflation is 4.3%, well above the EU average.

The deal has political benefits for PiS too. Initially sold as a PiS initiative, it was rebranded as a joint effort with its 2 junior coalition partners, papering over cracks the relationship. The coalition still leads in the polls, ahead of the fragmented center.

=== Greece as the EUs model student

The EU machinery has praised Greece for its handling of the pandemic. This is a big shift for the thrice bailed-out country, which was seen as the rebel of the bloc in the far-left Syriza days of 2015-19.

Mitsotakis of New Democracy, the center-right PM since 2019, has set himself up as a friend of the technocratic EU world. He was elected on an implicit mandate to make Greece into a "normal European country" again.

A decade on from the EU crises, Greece had its finances in order long before C19. Bond years are near record lows. The ECB willingly buys its debt. Ivy league nerds run the show. Years of bludgeoning means that Greek officials know how to tick the EUs boxes - its plan for spending EU19 funds was thousands of pages long.

Greece might have blotted its record with the dire conditions imposed on migrants on islands, as well as illegal "pushbacks" to source countries. But the harshness seems to suit Brussels. VDL hailed Greece as "Europe's shield".

Clientelism and nepotism are still a big problem. Activists claim a rise in police brutality since ND came to power. Media freedom is 4th lowest in the EU (Malta, Hungary and Bulgaria are lower). But again the EU doesn't seem to care too much while the economy is not falling apart.

The EU is a political, not a moral, policeman. As long as countries go with the flow, and don't try to change it like Syriza did, they leave well alone.

== Business

=== 2nd tier tech firms

Snap (of Snapchat) IPOd in 2017 and promptly went into a tailspin. By 2018 the share price was less than a fifth of the IPO price. Since then it's turned around. It has surprised analysts several quarters running. The share price is up 208% in 12 months.

The comeback is part of a broader trend of strong growth in 2nd-tier tech companies, even relative to that of the 1st tiers. This confounds the predictions of many that tech would be a winner-takes-all industry, with a few firms taking all the pie.

Technology adoption and cloud computing has allowed forms to specialise, creating big markets. Twilio provides text, voice and video comms to 200k other firms, including other tech firm. They are providing off-the-shelf capabilities which would be very hard to build in-house, and doing so in a IaaS plug-and-play manner. The pattern is also discernable in China.

The techlash against the 'GAFAM' firms has discouraged them from making big takeover bids, which has in turn prompted more T2 firms to list, bucking the prevailing trend of staying private for as long as possible.

T2 firms are getting better at building 'platforms' - an closed ecosystem of users which enable buyers and sellers to transact. Doing so generates network effects and virtuous circles (called flywheels in the jargon), and providing moats against copycats (including the 1st tiers). Shopify doesn't compete with Amazon. Zoom introduced "Zapps" (Zoom Apps). Snap is positioning itself as a 'superapp' on the model of TenCent's WeChat in China. Saleforce is buying platform-y capabilities.

Others (the Economist puts 42 in the list, most of which grew by double digits during the pandemic)

* Zoom
* Shopify
* Pintrest
* PayPal

== Finance

=== Big banks and crypto services

Crypto had a tough week. Tether's admitted just 2.9% of its coins are cash backed, calling its dollar peg int question. Tesla stopped accepting BitCoin over environmental concerns. China warned its financial industry away from crypto. Bitcoin fell to $30k, down by half from April, dragging most other coins with it. Many exchanges couldn't handle the volumes, calling into question the markets suitability for institutional investors.

Banks are venturing into cryptoland. Goldman relaunched its cryptodesk, shut down in 2017. Citi, BNY, StateStreet and JPM are all making noises. Why? First, American regulators have been setting out what services banks can provide, which gives some firmer ground to stand on. They say custodial services are OK, and derivatives which reference coins (classified as commodities) can be traded.

Mainly though, banks are interested because customers are interested (maybe obsessively). Many who traditionally work through banks want to invest, but right now have to do so through fintechs and startups. They would be more comfortable if the banks could handle it.

The derivatives and custody parts are simple enough - though the latter requires significant tech investment. The next level is where banks hold crypto on their balance sheets. Given the recent volatility regulators may not allow it. But banks could still act as a shopfront, relying on the infrastructure and balance sheets of other.

=== Living without LIBOR

In hindsight LIBOR was an odd thing to have become the global standard for benchmarking interest rate. It's an estimate of the rates big London banks lend to each other in a small and obscure corner of the money markets.

It provides "fixes" for 5 currencies daily for various periods. It will stop fixing all except USD at the end of 2021, and USD from June 2023, after the 2012 manipulation scandal. A replacement is needed.

There is a long list of candidates. The leading ones are

* For USD: The Secured Overnight Financing Rate (SOFR)
* For GBP: The Sterling Overnight Index Average (SONIA)
* For Yen: The Tokyo Overnight Average Rate (TONAR)
* For CHF: The Swiss Average Rate Overnight (SARON)
* For EUR: The Euro Short Term Rate (ESTR)

All are 'risk-free' rates. But there are some differences. SONIA ESTR and TONAR are based on the unsecured deposits banks in the respective regions use for daily liquidity. American and Swiss banks rely on repos, and SOFR/SARON are based on that.

There are alternatives to SOFR, whic might be OK for big national US banks, but not so much for regional banks that rely on unsecured debt and don't use repos much. For them, AMERIBOR, which is based on lending rates of these banks, is available. Indices produced by Bloomerg and ICE are based on long-term bond yields, for banks that use that more than repos.

These other indices for USD, though, have the same problems as LIBOR did: if the transactions which it references dry up the rates get iffy. The repo market, on the other hand, is ginormous, at $1trn per day. AMERIBOR and ICE equivalents are $2.5bn and $15bn respectively.
