= Notes on Elements of Clojure
By Zach Tellman

== An outline in headings

* Names (20 pages)
** Data (6)
** Functions (3)
** Macros (3)
* Idioms and conventions (38)
** Inequalities: Prefer `<` (2)
** Support 0, 1 and 2 arities for accumulators (4)
** Option maps over parameters (5)
** Hide your `binding` (7)
** Use `atom` for mutable state (5)
** Use redundant `do` for side effects (2)
** Use narrowest possible accessors (2)
** Use `letfn` for mutual recursion (2)
** Make Java interop obvious (1)
** Use `for` for cartesian product (2)
** Use `nil` carefully (5)
* Indirection (33)
** Method dispatch (4)
** What is abstraction? (3)
** A Model for Modules (9)
*** Models (4)
*** Invariants (1)
*** Assumptions (1)
*** Conventions (1)
*** Interfaces (1)
*** Environments (1)
** Consequences of our model (9)
*** To abstract is to treat things which are different as equivalent (1)
*** Models reflect our perception of their environment (0)
*** A module is useful only if its assumptions are sound (1)
*** To know a modules assumptions, we must know it's model (1)
*** A module can't prevent itself from being misused (0)
*** If a model ignores too much we can grow it, replace it, or narrow its use (0)
*** Models are useful because they are small (1)
*** Starting from scratch is costly (0)
*** If a module makes unrealistic assumptions, users can wrap, create conventions, or discard (0)
*** If it can't be discarded, it may destroy what it doesn't reflect (1)
*** Software would be easy if things never changed (1)
** Systems of Modules (6)
* Composition (26)
** Unit of computation (7)
*** Processes provide (some) data isolation (1)
*** Processes provide (some) execution isolation (2)
*** Example: a REPL (1)
*** Example: a web service (1)
*** Example: a frontend app (2)
** Building a process (9)
*** Pulling data (2)
*** Transforming data (1)
*** Pushing Data (4)
** Composing processes (7)

== Terms

* Abstraction
* Assumption
* Context
* Data scope
* Deductive
* Environment
* Function (push, pull, transform)
* Idiom
* Indirection
* Inductive
* Interface
* Invariant
* Model
* Module
* Name
* Narrow
* Process
* Purpose and implementation
* Natural and Synthetic names
* Referential transparency
* Tacit Knowledge

== Intro

*Tacit knowledge* - we know more that we can tell. Knowledge deeper than a linear chain of logic.

== Names

Names should be

* *narrow*: excludes things it can't represent
* *consistent*: easily understood by someone familiar with the context

=== Implementation and Purpose

Names should describe _purpose_ not implementation

Implementation is self describing. `(get-sol-jupiter m k)` is no more communicative than it's implementation `(get-in m [:sol :jupiter k])`.

Purposeful name: `(jovian-moon galaxy moon-name)`

Describing purpose without implementation is the first form of *indirection*.

=== Signs, referents, senses

Names consist of:

* the *sign* - the textual symbols
* the *referent* - what the sign refers to (a thing or a set of things)
* the *sense* - _how_ the sign refers to the referent. The _properties_ of the name.

The second and third roughly correspond to implementation and purpose.

'Sense' is quite subtle, getting into the context in which the name is defined. For example, we can say

  a = 42
  b = 42

`a` and `b` are different signs which point to the same referent. In a mathematical sense we can plausibly say that `a = b`. In programming it will likely be the case that we expect at least one of these to _change_. In this sense, saying `a = b`, even if right now it happens to be the case, would be less universally correct.

Say we have a name which we give sign `id`. 

* The _referent_ might be the set/type of UUIDs (128bit values). 
* The _sense_ is the property of uniqueness.

The sense of a name can also be implied by the surrounding context, though obviously you need to be careful with this.

There can be inconsistencies between a sense and referent. A UUID implementation of `id` is not going to guarantee the uniqueness property. The truly correct sense (and therefore name) would be `probably-unique-id`. But this would go too far. We have to make judgments about the probability and impact of these inconsistencies.

=== Dealing with multiple contexts/senses

Consider the name `student`. The sense of student might be different in different contexts: admissions office, bursars office, faculty. Within each context, the sense may be clear. But if we have a scope where we need to deal with multiple senses, this is problematic because the senses can become confused.

We might _qualify_ the name by putting each in it's own namespace (`admissions/student` etc.). But maintaining the clarity of separation can be difficult, and will require constant mental effort. Accidental conflation will cause subtle problems.

We might try to avoid separate contexts by ascribing the name `student` to only the most general case - here probably admissions - and using it in all contexts. But this harms the narrowness of the name.

We might just specifically avoid the general name `student` and create a new name for each of the 3 senses, thus maintaining the one-to-one correspondence between name and sense.

=== Natural and Synthetic names

Student is a particularly problematic name in terms of maintaining the sign-sense unity, since it is a *natural* name. People can and will bring in senses that are from other contexts based on common everyday usages. 

On the other hand, the existing senses that are in peoples heads provide the ability to *reason by analogy*, which is a powerful tool for comprehension.

Creating *synthetic* names avoids the risk of bringing in outside senses, but you lose the ability to reason by analogy. The decision about which to use is a tradeoff between accessibility and the potential for misconception.

=== Controlling the referent

When you name immutable data, you control sign and referent, but not sense (which you never really can).

When you name a function parameter, you control the sign (parameter name), but not the referent, which is whatever the client passes. You might want to enforce referent invariants at the top of the function - typically at the boundaries of your system where you have less control about what is coming in. Types do some of this for you, but usually not a la carte, and usually not with a fine brush.

Let bounds (locally scoped names) can be helpful in providing very *local indirection*. If the sign of the name (the left hand side) is good, the programmer can ignore the right hand side for the most part without sacrificing comprehension. The big caveat is that you _avoid side effects_. Having side effects in the RHS completely eliminates this property.

=== Not naming things

Names are hard. Don't find names if you don't have to. Intermediate variables, especially where they do not represent meaningful purposes in-and-of themselves, should not be named.

A large function is an assertion that it cannot be broken up into well-named pieces.

=== Extremely general names

* `x`: a value which can be anything, any type. Or which can be many types
* `xs`: a sequence of anything
* `m`: a map of key to any value
* `f`: an arbitrary function
* `[a b c ... & rst]`: a uni-typed sequence

The generality of a name implies the generality of the functions that should be used on it. If your name is `x`, you can use `str` `=` `hash` on it, but probably not much else. If you start to use functions that imply a more specific implementation (e.g. `+`), change the sign to narrow the implied referents the name can take (e.g. `num`).

=== Sequences, maps, tuples

* `student`: denotes a collection (usually a map) which has a well defined minimum set of keys and values.
* `students`: a collection of students. Usually a collection will have shared properties (e.g. attend the same class), and if that is not clear from context it should be made explicit in name of documentation.
* A well defined map of keys with type X and vals of type Y should be named `x->y`, e.g. `class->students`. This can apply to nested maps: `department->class->students`
* A tuple of an x and y should be `x+y`. `tutor+student`, a sequence of these: `tutor+students` - though notice the ambiguity, which could be removed with a more synthetic name: `tuteleges`. This would need to be documented. Generally you want to avoid doing this until absolutely necessary.

=== Function names

*data scope*: any data we can see from within our thread. function params, let bounds, closed-overs, global vars.

Functions can 

. pull new data into scope, 
. transform data already in scope, 
. push data into another scope. 

A function should only do one of these things (pushing and pulling in a single function might be done as an optimization).

* A function that pulls or pushes should be named with a verb.
* A function that pulls should describe the data it returns
* A function that pushes should describe the effect it has

`get-payload` is a pull, `delete-payload` is a push. `compress-and-get-payload` does both.

Transform functions shouldn't have verbs where possible. Specify what it returns, e.g. `md5-hash`, or if you need to specify the input to the transform, `payload->base64`.

Often you will have to use a verb though. `(add-student university department student)->university`.

=== Namespaces

If the namespace is limited to dealing with payloads (and is named as such) you can omit the payload part of the name and use `get`, `delete`, `compress and get`. Provided you specify and exclude any name collisions with a core function (`get` is a likely one here). 

Functions in a namespace should operate on a common data-type, data scope or both. This gives the namespace cohesion.

Avoid adding namespaces unnecessarily, since it adds cognitive burden. Combined with the previous statement, this implies that you should also limit the number of different types/scopes in your program, which is also a good idea. 

== Idioms

Software is layers of indirection. To understand more, you must dig down into lower layers.

In well designed software, the lessons you learn in lower layers should add _detail_ to the lessons from higher layers, but they will never _invalidate_ lessons learned from higher layers. 

*Idioms* provide a mapping between code structure and intent.

* Prefer `<` and `<=` over `>` and `>=`
* Support every arity of a monoid `(f a b) -> c`: `(f) -> id` `(f a) -> a`
* Possibly support higher arities with variadics by self-calling `reduce`: `(reduce f (f a b) rst)`
* Also try to do this for accumulators, like `conj`: `(f A1 b) -> A2`, `(f A1) -> A1`, `(f) -> Aid`.
* Use option maps not names parameters.
* If you have mutable state, use an atom
* explicit (potentially redundant) `do` implies side effects
* use `letfn` for mutual recursion
* make interops obvious
* use `for` for cartesian products, but when you do, avoid the special clauses (`:let` etc.)

=== Referential transparency

Laziness relies on it. Side effects break it. Side effects mean we need to think about more than just what an expression returns, we need to think about how and when it does it.

Dynamic scope, binding, obviously, also breaks RT.

=== Atoms and refs

With ref's (using STM) you're coordinating between state constructs. With Atom (using CAS), you're working on a single state construct. Thus, you can accomplish the same thing as with refs by putting them into a single atom, at the cost of throughput/retries. Since the number of expected retries increases rapidly over 60% utilization, an atom will reach that threshold faster than two refs holding values separately.

But this is almost an edge case, you're talking hundreds of thousands of request per second before this becomes an issue. Your network will usually become a bottleneck before this does.

STM is more difficult to use effectively. It can have weird and subtle bugs. `commute` can can be used inappropriately. Just use and atom. Transactions also make it more difficult to get a consistent snapshot of state. You can't just `(map deref my-refs)` because a transaction might occur during the process. You need to wrap the _read_ in a transaction (`ensure`).

=== Using the narrowest accessor

`(map first x)` and `(map key x)` might be functionally equivalent, but the latter is narrower - it specifies that the x is a map, whereas in the first it could be any collection of collections. This is useful for the reader.

Using a generic accessor, we imply that it doesn't matter which collection they are used with. If it _does_ matter, you, the programmer, should indicate it by using a narrower accessor. 

=== Be very cautious when dealing with nil return values

Clojure has many 'nil-friendly' functions: functions that happily accept or return nils.

`nil` is an absence. An absence of what depends on context.

* absence of seq: `(conj nil :callisto)`
* absence of things _in_ a seq : `(count nil) => 0`
* absence of map: `(assoc nil :callisto 1610)`
* absence of truth: `(if nil :a :b) => :b`
* absence of something we tried to look up `(get {} :callisto) => nil`

This context requirement means we can't consider a nil returning sequence in isolation. We have to make sure our downstream functions handle it, interpret it in the right context.

[source,clojure]
----
(-> keys->numbers
    :c
    (conj 8 9 10))
----

Here, if there is no key `:c` in `keys->numbers`, it will produce nil, with the intended meaning that 'there is no value associated with this key'. However the conj will interpret nil in the sense of 'an empty sequence'.

So here if `:c -> [1 2 3]`, the above returns `[1 2 3 8 9 10]`

And if `:c -> nil`, `(10 9 8)`

We must mitigate the nil case by providing explicit defaults.

Composing nil-friendly functions can obscure the result. If you have a chain of 4 functions, each of which can both accept and return nils, and you get back a nil, what does that represent? At which point did it get nilled? You can't tell, you can't reason about it. You have to test each case.

Again, when you have these chains, you have to make specific 'nil interpretation' guards at well chosen places through your code.

`(-> solar-system :jupiter :callisto :mass)`

`(-> solar-system :jupiter :callisto (:mass :mass-not-found))`

Note this makes your return value a `number-or-keyword` type. But that's at least more explicit than `number-or-nil`

Thus, *avoid* the common idiom `(when x ,,,)`. This is buck passing. If it makes sense in context to return an empty collection, do that. Otherwise throw an error.

== Indirection

Indirection separates what and how. It has the following qualities

. when implementation is complicated or subject to change
. gives us freedom to change detail without users having to care
. defines semantic layers in software, inviting the reader to stop when they think they know enough

Two fundamental tools: *references* and *conditionals*

=== References

A reference is a value that points to another value (the referent). It can be dereferenced at compile-time (a name) or runtime (a pointer). In both cases a reference can point to nothing.

=== Conditionals

Conditionals shield callers from implementation detail.

[source,clojure]
----
(defn nth [x idx]
  (cond
    (string? x) (.charAt ^String x idx)
    (instance? List x) (.get ^List x idx)
...))
----

Here, the caller doesn't have to think about whether what they are passing in is a string or a list - in both cases they want back the nth value of the input. The conditional takes care of the detail for them.

Conditionals can segment behavior across types, as in this case, or unify across types.

A reference _conveys_ values, a conditional _decides_ based on values.

A reference is *open*, whereas the conditional is *closed* - you can only change the behavior by changing the underlying code.

Conditional code is _ordered_. Predicates in the conditional may overlap. Any open decision making process must be unordered, thus we can't make conditionals open.

You can make an open decision making process by making it unordered. That means predicates must be disjoint. Which means you need distinct keys which map to behavior, really. We'll call this a *table*, with unique keys. But you need to enforce this uniqueness, so you either make it private (which rather defeats the object), or extensible using only private keys so no one can shadow behavior.

Conditionals avoid this by by solving conflicts through ordering. So conditionals are useful *because* they are closed.

=== Method dispatch

=== Abstraction

Indirection is a mechanism for creating abstractions. But this is a slippery term.

A common definition is from C.A.R Hoare, in _Proof of Correctness of Data Representation (1972)_. He distinguishes

* concrete representation: the internal model
* abstract representation: the interface it exposes

The first is mapped to the second via an _abstraction function_.

A concrete representation can have an _invariant relation_: Something that is true of the concrete representation in all cases. To determine if a method is correct, one need only consider the internal model and it's invariants. As long as all other methods maintain the invariants, you're all good.

Invariant relations allow you to change the internal model without impacting the interface. All your method implementations have to be changed to meet the new invariant. But that doesn't impact the API.

The idea of abstraction above is concerned only with self-consistency. It does not acknowledge that the abstraction, in reality, will be used in a context.

Consider early clocks. Early clocks had to sit on flat surfaces, couldn't be moved rapidly, had to be regularly wound, and couldn't be subject to rapid temperature changes. These are *not* invariants, because they can't be enforced by the clock. They are *assumptions* the concrete representation of the clock makes about its environment to be able to provide it's abstract representation (the time). Put the clock on a ship, and all of these assumptions just stop working, breaking the abstraction.

_Self consistency of the internal model is not enough for software_. The context always matters. We need the models to be _useful_ as well as self consistent. And while self-consistency is objective, utility is totally subjective.

=== A Model for Modules

Expanding on Hoare's definition, we can say most software abstractions are *modules*, having

* model - collection of data and functions
* interface - means of interaction
* environment - everything else

Models have *assumptions*. It should have *invariants* that enforce those assumptions.

==== Deductive and Inductive Reasoning

Physics aspires to deductive reasoning, mapping the environment into a model, then using the model _predict_ things about the environment. Conclusions in deductive reasoning are *necessary* - if they're wrong, it must be because our initial assumptions are wrong. But physics isn't, strictly, deductive. Newtons physics assumes a Gravitational constant, and that assumption can be wrong. Be we know also that the fundamental _mechanics_ of the physics are wrong. The model is wrong.

In software, post the AI Winter, deductive reasoning has largely given way to practical solutions and inductive models - that is, reasoning by analogy. Conclusions from induction are *contingent* - allowed to be wrong. The inductive model never predicts, only _compares_.

Inductive systems are both simpler and more robust. But they come at the cost of constant observation of the analogy you are drawing. It is a price worth paying.

To make a deductive model, you must reduce the problem to arithmetic or first order logic. It is difficult to create a deductive model that is useful, because real world problems are not generally reducible to this.

==== Invariants

We only want our model to represent models that can be found in the environment. We can enforce invariants on our _model_, but not on the _relationship_ between our model and the environment.

Our 'email' field must have an `@` in there somewhere, not be any string. This we can do easily with regex. But what can be found in the environment are _valid_ emails, so we want to narrow our representable set to those. That is more difficult to do, because it can never solely be determined within our model, so we have to reach out to the environment, via a confirmation email (even then, the environment can 'drift'). 

==== Assumptions

Omissions from a model are things that modeller has decided to not materially impact operation of the model.

==== Conventions

If a model doesn't hide an assumption, the users must enforce it. This can be done by establishing conventions. C++ RAII. Conventions are not a good solution for flawed assumptions.

==== Interfaces

The means by which the model and environment interact. These can be formal (e.g `defprotocol`) but also effects and shared state: printing, logging, atoms, network requests. All are methods where the software changes, or is changed by it's environment.

Interfaces are the _sense_ of the module. They should change much more slowly than the module itself, and only ever grow. They should be narrow, hiding much.

=== Consequences of our Model

To abstract is to treat things that are different as equivalent. If we find two tree which our model says is equivalent, we can apply our understanding of the first to the second. We use existing knowledge in novel situations, conveniently ignoring some differences. We must decide which differences to include, based on the purpose of the model.

Judgement of the usefulness of a model is based on the environment as it is, and as it will be. We should describe, upfront, our subjective understanding of the environment.

== Composition (p95)