= An Enquiry Concerning Human Understanding
By David Hume

== Content

. The different types of philosophy
. The origin of ideas
. The association of ideas
. sceptical doubts about the operations of understanding
. solutions of these doubts
. probability
. the idea of necessary connection
. liberty and necessity
. the reason of animals
. miracles
. A particular providence and a future state
. the academical or sceptical philosophy

== Terms

Moral philosophy: the science of human nature

Metaphysics: The profound and abstract philosophy

Human nature: The operations of the human mind.

Thought / Idea: 

Impression

Resemblance
Contiguity
Cause or Effect

Relation of Ideas
Matters of Fact

== On the different types of philosophy

=== Easy and profound philosophy, and the superiority of the easy

Moral philosophy is the science of human nature. It has two flavors.

The first considers woman as born for action, and as influenced in his actions by taste and sentiment. She pursues and avoids objects according the perceived value of these objects. Philosophers view virtue as the most valuable of objects, and expend many words in talking it up in an effort to convince us to take actions that will lead us to virtue.

The second consider woman as a reasonable rather than active being. Philosophers aim to shape our understanding rather than change our actions. They aim to examine human nature to find the principles which regulate our understanding and make us view object with approval or blame. They think that the foundations of morals and reasoning can be clearly defined and fixed. It is for them frustrating that we talk of truth, virtue or beauty without being able to determine and define the sources of these things.

The first is easy and obvious, the second is abstract and abstruse. For most people, the former will be seen as more agreeable and more useful in daily life. The second, in fact, vanishes on contact with the real world.

The easy philosophy has proved more durable through history. A profound philosopher, when she makes a mistake in reasoning and arrives at a conclusion that contradicts common sense, will push on with her reasoning to a conclusion, and use that conclusion as the basis for another line of reasoning, always straying further from truth. The easy philosopher only needs to check her conclusion against common sense to detect her error, and quickly correct herself to the right path.

The philosopher and the ignorant are  viewed as contributing nothing to society. The most perfect character lies between the extremes, with ability and taste in books, company and business. Compositions of the easy philosophy, which are comprehensible and applicable, are the best at cultivating this character.

Man is a reasonable animal, and draws nourishment from science. But because the bounds of human understanding are narrow, little satisfaction can be gained from this. Man is a social animal. But she cannot always be in good company. Man is an active animal, and must engage in business and occupation. But she needs relaxation. Nature points to mixed life as the most suitable one, and punishes those who focus on one at the expense of the others.

> Indulge your passion for science, says [Nature], but let your science be human, and as such as may have a direct reference to action and society. Abstruse thought and profound researches I prohibit, and will severely punish, by the pensive melancholy which they introduce, by the endless uncertainty in which they involve you, and by the cold reception which your pretended discoveries shall meet with, when communicated. Be a philosopher; but, amidst all your philosophy, be still a man.

So profound reasoning, or _metaphysics_, is rejected by humanity. Can we make an argument in its favor?

=== An argument for profound reasoning

The practical argument for metaphysics is that without the profound, the easy philosophy can't attain sufficient exactness in its reasoning. It is limited to presenting pictures of human life in various situations, and from that situation assigning praise or blame. But knowledge of what lies beneath the surface helps us better express that surface.

As an analogy: The artist may draw pictures of people from what she sees. But by studying the science of anatomy, what lies _beneath_ the skin and clothes - skeleton, muscles, joints - she is able to better draw what she can see.

> Accuracy is, in every case, advantageous to beauty, and just reasoning to delicate sentiment. In vain would we exalt the one by depreciating the other.

As the artist uses the accuracy of anatomical science to improve the beauty of art, the philosopher can use just but abstract reasoning to improve society by using it to inform the easy and practical philosophy.

Even without a practical argument, the pursuit of the profound shouldn't be rejected. It's harmless enough. It might be painful and fatiguing, but as strenuous physical exercise can give great pleasure, so can the great mental effort. Neither have direct object beyond that pleasure, but so what?

It is objected that abstract philosophy is _not_ harmless. The nature of its abstraction means it's a constant source of uncertainty and error. It's not a proper science, just an expression of human vanity and hubris, or even an effort to obscure challenges to dogma and superstition. So the field should be abandoned.

Shouldn't we draw the opposite conclusion though? Those who use the abstract reasoning in this way will not _stop_ doing it until we take the battle to them on their own ground, finding the methods with which to refute and disprove their erroneous arguments, and bring the exactitude we want. History teaches us that, even when a subject seems impenetrable to science, concerted effort over the generations can punch through the wall of darkness and bring the light of reason. 

For millennia, the astronomers contented themselves with describing, from observation, the motions of the planets. Eventually Newton came along, and by the force of reason was able to also determine the laws and forces which govern that motion. This pattern has repeated itself in many spheres, and there is no reason to think that human nature is immune.

The only hope of removing the abstruseness is to continue to enquire seriously into the nature of human understanding. This is what this book will attempt to do.

=== Human nature and the operations of the mind

It is remarkable that, despite being the thing that is closest to us, the operations of the mind are so resistent to reflection. We cannot see in them the lines and boundaries which discriminate and distinguish them. When we try, they seem shift under our gaze like smoke.

The aim of this work is to propose some model of classification, to delineate and distinguish the parts and powers of the mind, to allow us to make this reflection possible.

I take as our starting assumption that such a classification of powers and faculties of the mind is possible at all. As evidence for this I point to some delineations that already exist, without the exactness which is our goal, in the common philosophy: The distinction between will and understanding, or the imagination and the passions. Finer and more exact distinctions can also be found, though with much more difficulty. footnote:[Paragraphs 9 and 10 of the original work are not included here. They labor the justification this is a worthwhile endeavour without adding much to what has already been said.]

== The origin of ideas

(11) There is a difference between a sensation (feeling the pain of excessive heat) and the recollection of that sensation afterwards, or the anticipation of that sensation by imagination. The former will always have more force and vivacity. The most lively thought is still inferior to the dullest sensation.

Non-physical sensations can also be so divided. The _recollection_ of anger is only every a shadow of the actual sensation of anger. 

(12) We will divide all the perceptions of the mind into two classes, distinguished by their degrees of force and vivacity. The less forcible are *Ideas*. The more forcible are *Impressions*.

(13) At first glance human thought may appear unbounded. We can imagine monsters as readily as we can real creatures. 

Actually the limits of imagination are bounded by ideas we have, which we can creatively combine. Though a mountain of gold does not exist, we can imagine one by joining the two ideas 'gold' and 'mountain'. But we had to have had the *Simple ideas* (i.e. those which are ultimately formed of Impressions) of 'gold' and 'mountain' to create this *Compound idea* of the mountain of gold (which can have no corresponding Impression).

Consider God: An infinitely intelligent, good and wise being. This is a extension of the idea of our own mind, augmenting it without limit with the ideas of intelligence, goodness and wisdom. 

Any thought or idea we have can be decomposed into simple ideas.

(14) I present two arguments to support this theory:

First: Were it not true, it would be easy to refute by presenting an idea which cannot be so decomposed. footnote:[He goes on to present a counterexample in (16) and dismisses it out of hand!]

(15) Second: If we come across a person whose sense organs are defective, the person does not have the capability to create Ideas based on Impressions from that organ. A blind person has no Idea of color. If a blind persons sight is restored they will have no problem imagining color.

(16) There is a counterargument that would suggests we _can_ create ideas without corresponding impressions. Suppose that a woman has lived 30 years and has seen many shades of blue in that time, except one specific kind. Suppose that examples of all the different shades of blue _except_ the one she isn't familiar with are placed before her, from darkest to lightest. Would it be possible for her to imagine the missing shade of blue without having ever perceived it? It is absurd to suggest she would not.

This, then, is a Simple Idea created without a corresponding Impression. The counterexample is so particular, though, that it's not worth abandoning the general idea. footnote:[This seems to me very explicable. The simple ideas which are at play are not the colors themselves, but the idea of shade (light and dark) and of pigment mixing. If the woman is familiar (by impression) with the idea that mixing of two shades results in the averaging of those shades, this could be applied to coming up with the idea the 'missing' color without ever physically seeing it.]

== The association of ideas

(18) There is some principle of 'connection' between the different ideas in our mind. One idea leads to another. Our minds do not jump randomly around.

(19) There are three ways that ideas can be connected together: _resemblance_, _contiguity_ in time or place, and _cause and effect_.

Some examples:

* A picture of something triggers the idea of the thing in the picture (resemblance)
* A mention of one room in a house introduces the idea of the the other rooms (contiguity)
* The thought of a wound introduces the idea of the pain that follows it.

Proving that these are the only three is tough. We can only look at examples.

== Sceptical doubts concerning the operations of the understanding

=== Part 1

(20) All objects of human reason or enquiry can be divided into two kinds: *Relations of Ideas*, and *Matters of Fact*.

Relations of ideas are discoverable by thought alone, without needing to look around at the universe. Maths falls in this category: _the square of the hypotenuse is equal to the square of the two sides_, and _three times five is equal to half of thirty_ don't need any 'outside' facts to demonstrate their truth. There is no possibility that a right-triangle that doesn't have this property will be discovered.

(21) Matters of fact _do_ require an examination of the universe. When we repeatedly observe a thing we are likely to label it as a 'fact'. They are not _provable_, in the sense that a counterexample could at any time disprove it. _Swans are white_ is a statement informed by repeated observation, which is immediately disproved by the first observation of a black swan.

Many matters of fact are based on our direct impressions, or our memories of those impressions. But many are not. For example, a woman believes her friend is in France, but she has _seen_ that friend in France. That fact has not come from direct sensation.

What is the nature of the evidence which causes us to declare a matter of fact that is not based on direct impression?

(22) All reasoning concerning matter of fact _not_ based on direct impression seem to be based on the _cause and effect_. Ask someone why they believe as fact something they have not observed and they will give you as a reason some other fact. Were you to ask the aforementioned woman why she believes her friend is in France, she would mention an email she had received from her friend, or a conversation she had had with the friend before he left.

If an island with no people on it is believed to one have been inhabited, the reason for that fact will be that artifacts of their habitation have been found by someone.

If you are in dark room and converse with a voice speaking rationally, you will infer that there is another person in the room with you. footnote:[obviously written before the time of radio communication]

(23) If all our reasoning of facts is based on cause and effect, this raises the question of how we arrive at the knowledge of cause and effect.

I propose that this arises entirely from our experience of objects being regularly and often observed as connected. Present to even the smartest of women an object that is entirely new to them, and they won't be able to figure out its causes and effect. footnote:[This brings to mind the episode of Black Books, where Fran gets an object of unknown purpose (to her and the audience), and spends the episode trying to figure out what it does. At the end of the episode Manny, with no apparent mental effort, clicks a button and lights a cigarette from the resultant flame. Presumably Manny's experiences of a similiar lighter allowed him to infer the cause (push the button) will lead to the effect (flame)] By the evidence of many funny YouTube videos, Children have to learn to infer from the light and warmth of fire that it is painful to touch. footnote:[Hume also gives the example of having to learn that water cannot be breathed. I have seen some evidence that this is not the case, that babies are from birth aware of this. Could this be experience from the womb?]

No object contains in its perceivable qualities, the cause which produce it or the effects it will produce. These things are entirely inferred from our repeated experience.

*Causes and effects are discoverable, not by reason but by experience.*

(24) The effect of gunpowder in the presence of flame, or the attraction of magnets: these are things which we can probably remember not knowing about, and we can readily imagine if we were presented with gunpowder or magnets before being aware of their properties, that we would be entirely unable to predict them.

This truth is less apparent in things which are presented to our experience from birth. For example that one billiard ball will, when hit against another, impart its motion to the second ball - we might imagine that we could have predicted this by pure application of reason without prior experience. However this is an illusion.

> Such is the influence of custom, that, where it is strongest, it not only covers our natural ignorance, but even conceals itself, and seems not to take place, merely because it is found in the highest degree.

(25) Consider the following reflections in support of the idea that the laws of nature are knowable only by experience.

If an object were presented to us and we were asked to predict the effect of it, what else could we do but consult our experience? Our mind must invent or imagine an effect, which must be entirely arbitrary.

The mind can never infer the effect from the supposed cause, since there is nothing to possibly connect them except experience. The motion in the first billiard ball is a separate thing from the motion of the second, and the only thing that connects them is the experience of the watcher. 

When you throw a stone into the air, and it reaches the peak of its arc, there is nothing to suggest _a priori_ that it will fall downwards rather than upwards or to one side.

*Every effect is a distinct event from its cause, and the effect cannot be inferred from the cause _a priori_*

(26) The utmost effort of human reason is to reduce the principles of natural phenomena to simple laws, and to move from particular effects to _general causes_ by analogy, experience and observation. But we will never be able to discover the causes of these causes, or be able to get to a satisfactory explanation of them. Elasticity, gravity, cohesion of parts, communication of motion by impulse: we probably will not be able to get beyond these as ultimate causes and principles, and we should be happy if we are able to trace specific effects back to these general causes.

> Thus the observation of human blindness and weakness is the result of all philosophy, and meets us at every turn, in spite of our endeavours to elude or avoid it.

(27) We started this section by distinguishing _relation of ideas_, such as geometry, from the _matters of fact_ we have been discussing. Could we use the accuracy of reasoning in the former to resolve the defects of the latter and lead us to knowledge of ultimate causes?

Unfortunately, no. All 'mixed mathematics' (that is, mathematics which involves descriptions of reality) supposes that the laws of nature are established.

For example, it is a law of motion, discovered by experience, that the force of any body in motion is dependent on its mass and velocity. A small force may raise the greatest weight if we increase the velocity of that force. Geometry _assists_ us in the application of this law by giving the dimensions of all parts involved. But the discovery of the law itself is entirely dependent on experience.

=== Part II

(28) Back to the original question: "What is the nature of the evidence which causes us to declare a matter of fact that is not based on direct impression?"

Our answer so far is that "They are founded on the relation of cause to effect". The next natural question is "What causes us to conclude that a particular effect follows from a particular cause?". To that we answered one word: Experience.

The question then becomes "What is the foundation of all conclusions from experience?". That is, if we see one event happen, and then see another event happen, what is it that leads us to conclude in some cases (but not others) that event one caused event two? This is a much harder question to answer.

We'll propose a negative answer: that our inference of a causal relationship is _not_ based on reasoning, or any process of the understanding. I'll spend the rest of this section explaining and defending this answer.

(29) 