= Rust Cheat Sheet

== Cargo

* `cargo build`
* `cargo run`
* `cargo test`
* `cargo new myapplication --bin`

== Modules and imports

* `use std::fs::File;`
* `use std::io::{BufRead, BufReader};`

* `mod day1;`

== Strings

* `input.trim().split(",");`, where "," is the separator

=== From vec of chars to string

[source,rust]
----
fn main() {
    let char_vector = vec!['h', 'e', 'l', 'l', 'o'];
    let str: String = char_vector.into_iter().collect();

    println!("{}", str);
}
----

=== From string-slice to a vec of chars

`let c: Vec<char> = str.chars().collect();`

or to an iterator of chars:

`caps[2].chars()`

`caps[2].chars().next().unwrap()` where caps[2] is a &str to get the first char of a string

=== String concatenation

[source,rust]
----
let mut filename = "resources/day".to_string();
filename.push_str(&day.to_string());
filename.push_str("input.txt");
----

=== Parsing a string to an integer

[source,rust]
----
fn parse_number_list(input: String) -> Vec<u32> {
    let input = input.trim();
    input
        .split("\n")
        .map(|s| s.parse::<u32>().unwrap())
        .collect()
}

//or 
let num: usize = line.unwrap().parse().unwrap();
let x = usize::from_str_radix(&bin, 2).unwrap()
----

== Command Line Args

[source,rust]
----
use std::env;

let args: Vec<String> = env::args().collect();
let file = &args[1];
----

== FileIO

=== Reading from a file

[source,rust]
----
use std::fs;
let filename = &args[1];
let contents = fs::read_to_string(filename).expect("File read error");
----

=== Reading from a file with BufReader

----
use std::fs::File;
use std::io::{BufReader, BufRead};
let f = BufReader::new(File::open("../input/day01.txt").unwrap());
----

* use `f.lines()` method to get a iter of lines

== Regex

[source,rust]
----
[dependencies]
regex = "1.4.2"

let re = Regex::new(r"(\d+)-(\d+) (\w): (\w+)").unwrap();
let caps = re.captures(line).unwrap();

cap[0] // is full string
cap[1] // is first match etc
----

== Numbers

* `my_num.abs()` Absolute value

=== Integer to string

`num.to_string()`

== Structs

=== Named Tuples / Tuple Structs

[source,rust]
----
#[derive(Debug)]
struct Password(u8, u8, char, String);
let Password(low, high, ch, pw) = pp;
----

== println! macro

* `println!({}, a);` prints `a` in format specified by type `fmt` method of `a => std::fmt::Display` 
* `println!({:?}, a);` prints `a` in format specified by type `fmt` method `a => std::fmt::Debug` 
* `println!({:032b}, a);` print binary format with 32 left padded zeros. `a => std::fmt::Binary` 

== Tests

[source,rust]
----
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_example(){
        blah blah blah
        assert_eq!(a, b )
    }
}
----
