= On the reconciliation of financial instruments

Asset managers hold financial instruments. With most of these financial instruments, two parties are involved. If a OTC bilateral financial contract is written, the first party is you, the second party is the other contractual party to the agreement. If you have bought securities on a market, you will likely have a custodian which holds the securities in your account. If you have purchased a notional amount of debt issued by a company, there will usually be an agent who is responsible for keeping track of your holding of that debt.

Both parties will maintain records of the instruments, sometimes in the form of physical certificates, but more commonly in the form of electronic records. Particularly as volumes of trades become large, maintaining these records accurately becomes difficult due to the messy nature of the trading process. Both parties have strong incentives to make sure those records are correct. Here are a few of the reasons why:

* Custodians are responsible for maintaining the record of the their customers holdings, and have a fiduciary (and legal) responsibility to show the 'correct' holding of their clients. Failure to do so will lead to reputational and financial damage
* Income streams on instruments are directed based on these records. If a clients record of holdings are incorrect, they will not get the correct amount of dividend or interest
* The management of a company's risk is dependent on an accurate record of the instruments they hold. If the record is incorrect, they will be unable to assess risk and project future liquidity.
* An accurate record of positions is necessary for trading. If a holder believes they hold 100 shares, but they actually hold 50, when they try to sell 75 shares they will have 'oversold' their position.
* A company's holdings are often used as the basis for other calculations or processes. For example, a hedge fund's holdings at its prime broker will be used as collateral for _leverage_ (liquidity) that the prime broker offers to the hedge fund. A prime broker can also lend out the securities of its client to third parties in exchange for a fee. OTC Derivate contracts under an ISDA agreement have margin requirements, where if the contract is 'out of the money', the client has to provide collateral to the other party. In all of these cases, if the position records are wrong, the consequent calculations or actions will also be wrong. 

The way the industry has settled on to maintain correctness of the records is by the 'periodic reconciliation'. That is, party A will send party B its records of the positions held, and vice versa, and each party will compare records to see if they agree. In this post, the records exchanged will be referred to as *assertions* - Party A _asserts_ that they have a contract with Party B with these attributes. If Party A and Party B disagree on a certain record, this is called a *break*. A break results in a *dispute* between the parties, and the parties will aim to resolve (or reconcile) the dispute and solve the break, by examining and comparing their respective records of the history of that position.

Reconciliations can be done at different periodicities: daily, bi-monthly, monthly, transactionally (e.g when interest on bank debt is paid, the agent will send a notice containing the basis calculation of the amount paid, and the recipient will check that they agree with the calculation, explicitly or implicitly reconciling the positions)

The goals of reconciliation can be broken down like this:

* *Attribute Matching*: Party A records its contracts using a particular model. Party B records its contracts with a different model. Notwithstanding the difference in models, the parties must agree that contracts each model describes are 'the same'. To take a trivial example, if Party A calls the strike price of an option contract the "Strike Price", but Party B calls it the "Rate", then some mechanism has to exist that says "These two fields are meant to represent the same thing". These difficulties in these problems are difficult in proportion to the difference in the models. A wrinkle in this is that Party A will br trying to reconcile not just with Party B, but also with many other parties, all of which will have different models for their instruments 
* *Identity Matching*: Party A has a record of a contract. Party B has a record of the same contract. How do the parties agree they are talking about the same contract? This can be done either by having a mutually agreed identifier for the instrument (on public markets, ISINs, CUSIPs. On OTC contracts, a trade ID or "Universal Transaction Identifier" that the parties exchange when entering into the contract), or more weakly by a 'match on attributes' approach, where if certain attributes reported by each side agree, you decide you are talking about the same contract.
* *Dispute resolution*: Where one party determines that a break has occurred, there needs to be a process in place for resolving the dispute with the counterparty, and keeping records of that dispute resolution.

The problem can be broken into the following sub-problems:

. Assertion generation: How do get a list of positions that assert your holdings? 
. Assertion Exchange Mechanism: How do the parties exchange their assertions?
. Model conformance: Given the models for the positions of each party are different, how do you get to the point where you can compare like with like?
. Identity establishment: How do you decide that you are talking about the same contract as your counterparty?
. Dispute raising and resolution mechanism: Once you have identified a break, how do you create a dispute and forum for resolving it with the counterparty? Ideally you want to do this in a structured way such that the record of the resolution is maintained. So you don't want to do it by email or, god forbid, by phone. 
. Dispute publication: When you have identified a dispute on a particular day, other parts of your business will likely need to know that because it could impact their process. How do you inform them of the break? What information do you need to provide?  
. Handling changing models: Both you and your counterparty will evolve their models for representing positions over time as markets and internal requirements change. How will you handle those changes in a way that doesn't break your system?
. Known breaks: If you do a reconciliation today, and you end up with break which you have resolved but you know that due to timing the break will also show up in tomorrow's reconciliation, you need to be able to record that fact as a 'known break', so that if someone else is doing the reconciliation tomorrow they won't raise an unnecessary dispute. Likewise if, due to a changing model, you will technically be breaking with a specific field with a counterparty until the matching process is changed to account for that change, you might end up with hundreds of known breaks that you know are not 'real' breaks. Reviewing these 'false breaks' is a waste of time, so you want to have the system ignore them.
. Break severity: Some breaks are more serious than others. If you are asserting a position that the counterparty has no record of, that might require more urgent resolution than if the trade date of the contract you are asserting is off by a day. The severity of the same break might also be different depending on instrument type, timing (e.g. you might be fine if you are breaking for a few days in the middle of the month, but at month end you really need to be in agreement) and counterparty.
. Dispute investigation: You have a break. How to you figure out what's causing it? You need to be able to 'back trace' from the position you are asserting to the component parts of that position: the trades and transactions that comprise it, and transactions that _would_ affect that position but because of timing of booking are not yet reflected in it.

== Principles

We can lay out some principles that our reconciliation system should follow in order to be effective:

* The mechanism for exchange of assertions should be entirely automated. You don't want people sending Excel files around by email, both because it's extremely inefficient, and because of the risk of human error in moving the data in the files around.
* Identity matching should preferably be done by identifier matching, not by attribute matching
* 'man-in-the-middle' models should be created to which all assertions are conformed. This means you will need a model for each instrument type, and a separately configurable mapping _to_ the MITM model for each party and each instrument type.
* model mappings should be configurable by the user
* Reconciliations should be handled on negative basis, not a positive basis. That is, the only time a person should be getting involved in the reconciliation process is when there is a break. A perfectly matching reconciliation should imply that no human is involved at any point.
* Break back-tracing data should be available at the first presentation of the break. When a person is notified of a break in a position, the constituent parts of that position should be immediately accessible to the users.
* the dispute resolution process should be 'in-band' and automatically fired. When a break is noticed, both parties should be automatically notified of the break by the raising of a dispute, and as much information as possible about the context of the break provided.
 