= In praise of Idleness

https://harpers.org/archive/1932/10/in-praise-of-idleness/[Link to full text]

== Summary

An essay written by Bertrand Russell in 1932.

The idea that the working class give their surplus to a ruling aristocracy, so the the aristocracy may have the leisure to rule and advance civilisation, is immoral. Possibly this was neccessary for survival in pre-industrial societies. It no longer is.

The idea of work being virtuous and noble is a moral myth created by the ruling class to stop workers complaining that the aristos are taking their stuff. It is a myth believed by its creators as well as its targets.

== Quotes

> The road to happiness lies and prosperity lies in an organized diminution of work

> The conception of duty, speaking historically, has been a means used by the holders of power to induce others to live for the interests of their masters rather than their own. 

> The [First World] War showed conclusively that by the scientific organization of production it is possible to keep modern populations in fair comfort on a small part of the working capacity of the modern world.

> those whose work was demanded were made to work long hours, and the rest were left to starve as unemployed. Why? Because work is a duty, and a man should not receive wages in proportion to what he has produced, but in proportion to his virtue as exemplified by his industry.

> The idea that the poor should have leisure has always been shocking to the rich... When meddlesome busy-bodies suggested that perhaps these [15 hour workdays] were rather long, they were told that work kept adults from drink and children from mischief. 

== Notes

=== Part 1

* "The devil makes work for idle hands"
* There is too much work done, and the belief that work is virtuous is harmful
* The argument that those who can live off not working _shouldn't_ work, because it "takes bread out of the mouths of others" is wrong. Expenditure increases with income, and expenditure creates jobs
* The villain is he who saves. Investing in government bonds funds wars past and present.
* Investing in private enterprise is also destructive, because most businesses fail. So human labour is expended on things that don't add to pleasure.
* Spending that money on a party for friends would've made the attendees happy, and also provided employment for the caterers, entertainment etc.
* Work has 2 kinds:
** moving matter
** telling people what to do
* unpleasant vs pleasant, badly vs well paid
* second extensible: giving advice about what orders to give.
* The skill in the second is not knowledge of subject but of persuasion - advertising
* Europe: landed aristocracy. They are idle, but _not_ the idleness praised here: they are idle through the industry of others.
* History of civilization: the workers work, surpluses go to the priests and warriors. When there was no surplus, P&W still fed, workers died. Has only ended 'recently' in the west, post Napoleon at the earliest
* Our view on the virtue of work is shaped by this. It is the morality of slaves. The willingness to give up surplus is an imposed ethic to the benefit of the masters.
* Leisure is essential to the advance of civilization. The argument of the masters is that, by giving up surpluses to the masters, the slaves permit the masters the leisure to advance civilization.
* Modern 'technic' means that much less labour is needed to produce the necessities of life.
* The state organized economies and 'scientific organization of production' visible during WWI are an example.
* Might argue that this was financed by huge and unsustainable borrowing, which "made it appear as if the future was nourishing the present. But that, of course, would have been impossible; a man cannot eat a loaf of bread that does not yet exist." 
* Preserve the methods, without the need to supply the war, and you can cut working hours to 4 per day.
* Pin example, kind of bad IMO

=== Part 2

