= Simple vs. Easy

I recently saw a https://www.youtube.com/watch?v=doZ0XAc9Wtc[Conference talk] from Phill MV in 2016 about how he tried Clojure and why he went back to Ruby, which apparently triggered some soul-searching in the Clojure community at the time about the state of the language. 

The follow-ups include https://blog.appcanary.com/2017/hard-isnt-simple-ruby-clojure.html[Phill's own post], as well as commentary from https://lambdaisland.com/blog/25-05-2017-simple-and-happy-is-clojure-dying-and-what-has-ruby-got-to-do-with-it[Arne at Lambda Island], Eric Normand, and other well known people in the Clojure community on Twitter.

The debate was broad ranging, and I'm only talking about a small piece of this: Phill's statement in his follow-up article that 

[quote]
'Simple != Easy' Is One Of The Most Toxic Ideas Ever Introduced To Programming 

referencing the Rich Hickey talk https://www.youtube.com/watch?v=oytL881p-nQ["Simple Made Easy"] https://github.com/matthiasn/talk-transcripts/blob/master/Hickey_Rich/SimpleMadeEasy.md[[Transcript\]]. Intentionally hyperbolic for effect, obviously, but let's first look the what Phill is referring to, and then what he means.

There are a lot of ideas in Rich's talk, but the one under cursor here is essentially that programmers focus too much on what is _easy for them_, and not what good for the program (or construct) itself, especially over the long term. 

What is actually good over the long term for both programmer and program, he says, is simplicity.

[quote, Rich Hickey]
This whole notion of sort of programmer convenience, again, we are infatuated with it, not to our benefit...
We have to start assessing our constructs [the things we make and use] based around the artifacts, not around the look and feel of the experience of typing it in or the cultural aspects of that.

Phill's response is this:

[quote]
In practice, ‘Simple Made Easy’ is an elaborate excuse for making software that is hard to use...By separating “simplicity” from “ease of use”, and then establishing the primacy of simplicity, it gives people an ideological out to discount improving the user interface of our tools and artifacts.

We should pause at this point and clearly define up what simplicity and ease mean in this context. Absolutely watch the Simple Made Easy talk linked above, but in short the meanings are:

* Simple, as in not complex, where complex means something is 'braided together', intertwined, tangled, like you put three sets of earphones in your pocket.
* Easy means close at hand, quick for us to get, or familiar to us, or within our capabilities.

It may be useful context here that Phill is coming from a Ruby background, and the explicit philosophy of Ruby is 'Optimizing for Programmer Happiness'. Phill clearly subscribes to this, and takes it further, saying:footnote:[I have to mention one tweet of his: he says "I want to believe that Programming Isn't That Hard, Ya Know?". This was the only thing I saw in this debate that made me blink. I don't know how anyone can program for any length of time and think that it 'Isn't That Hard']

[quote]
All programming languages should strive to be fun and make programmers happy.

According to Rich, the programming community has a tendency to see an extra bit on those sentences: 'at the expense of all else.'footnote:[It's worth pointing out that Clojure programmers think Clojure _is_ fun, and it _does_ make them happy - Rich's motivation for creating the language was that existing tools and programming paradigms were making him extremely _unhappy_, to the point where he was considering quitting the craft altogether.]. I think it's fair to say that Rich disagrees with these statements, at least when interpreted like this.

Phill is saying that these two things, ease and simplicity, are _opposed_ to each other - that you focus on simplicity at the _expense_ of ease. I can see why he gets to that. I even think that in some sense it's correct. But it's missing some intermediate steps that need to be unpacked before we can loop back to address it. The intent of Rich's idea is hinted at by the title of the talk: it's "Simple *made* Easy", not "Simple *vs.* Easy".

Let's go back to the definition of easy. There were three examples given of types of ease: Something that is close at hand, easy to get; something that is familiar to you; and something that is within our capabilities.
    
*Q:* How do you make something that is hard to get, easy to get? 

*A:* You build NPM. This is totally feasible.

*Q:* How do you make something that is unfamiliar to you, familiar to you? 

*A:* You buy a book, you do some tutorials, you read the code. In other works, you learn how to do it. Again, totally feasible.

*Q:* How would you bring something that is beyond your capability to comprehend, _within_ your capabilities? 

*A:* You would have to get smarter, as in dramatically raise your ability to comprehend. Unfortunately this isn't possible.

This is where the concept of complexity/simplicity intersects with the concept of easy/hard. It's a problem of scaling factors. When you entangle ideas together ('complect' it in Rich's words), the difficulty in comprehending it grows geometrically. Ten things tangled together are much more than twice as tough to get your head around than five things. Our capacity to rise to this challenge by improving _our ability to understand_ just can't keep up. However you measure peoples ability to comprehend, a super-smart person is not orders of magnitude smarter than someone super-dumb. We need a different way to make things that are beyond our capability to comprehend easy.

A couple of times, Phill mentions that from the responses he got to his Clojure troubles from the community, he inferred they were saying he wasn't smart enough to 'get' it. I want to emphasize that's not what _I'm_ saying. It's not the individual smartness of Phill that is the problem. It's that when things start to increase in complexity, they eventually can't be comprehended by _anyone_, because of the way complexity scales in comparison to our ability to get smarter.  

The relevance of all this to programming is that we frequently (and increasingly frequently) have systems which are incomprehensibly complex, or use complex pieces, and we need a way to make them easy. 

One way to deal with this is to follow a useful programming pattern: create a detail-hiding facade, let tools and metaphors hide the complexity from us, intentionally sacrificing our comprehension of the thing behind it in the name of getting stuff done.

The inner workings of Ruby on Rails, for example, would be utterly incomprehensible to a newbie. But they can still follow the tutorial and build a twitter-clone, and after a while they will understand the metaphor that sits in front of that complexity. After a fairly minimal time you can be extremely productive.

Objects, as implemented in C# or Java, have mind-boggling semantic implications when you get into them. But you can - and have to - program with them without fully coming to terms with those complexities, which is possible by using the well established metaphors and patterns for thinking about them that have been developed.

It is totally understandable why the use of a detail-hiding interface seems reasonable here. In several contexts it's a fantastically useful tool for decoupling. As a C++ lecturer's t-shirt once said, 'I don't know, I don't wanna know'.

Rich's hypothesis, though, is that using this approach for hiding _complexity_ is a long term loser. At some point that complexity will come back to bite you.footnote:[But only over the long term. It doesn't matter for things that don't exist for long enough for that balance to shift] The alternative he proposes is that instead of hiding the complexity, you _eliminate it_, turning it into things that you _can_ comprehend. And you do that by either replacing the complex piece with some other thing or things that are simple, or by taking the complected thing and picking it apart into its constituent simple pieces.

From this you can see that simplicity as defined here is not _opposed_ to ease, it is an alternative strategy to _make_ things easy. Compared to the Phill Model of complexity masking, the Rich Model is certainly the more costly in terms of upfront investment, because you are committing to comprehending the artifacts that you use, which is extremely taxing.

The opposed ideas that Phill has identified are not 'simple vs. easy', but rather the clash between these two models of making the complex, easy.

Phill has further identified one of the consequences that has come from this: that the *tools* that arise under the Phill Model have that same aim of making the complex easy by masking  complexity, creating a facade around it that you can pick up quickly and be productive without having to do the decomplecting-then-comprehending exercise. 

The tools that arise under the Rich Model presume that the artifacts you are using are simple, and you can comprehend them, so there is no need to create a facade. If you use these tools without that understanding, you are going to have a bad time until you put in the legwork. Further, if your experience has led you to expect that the purpose of tools is masking of complexity (and the the thing behind the facade is too complex to ever understand anyway), you won't know that you are *expected* to understand, and will resent the obtuse and unhelpful nature of the tools. I believe is what Phill means when he says that focusing on simplicity leads to tools that are hard to use.

I think it's this fundamental disconnect that is at the core of Phill's critique of Clojure, and is also the reason for the frequent questions from new Clojure programmers like 'why is their no equivalent to Rails or Django in Clojure', 'Why are the error messages so bad' and 'why are there so few tutorials / documentation'. 

Most of the responses I saw from the Clojure side focused on the problems (in their view) of not having a Django, or unreadable stack-traces - programmer experience problems - and recommendations to make the tools easier to use, using a more Phill Model approach. And of course this _could_ be done. But I think it misses the point. It seems to be the case that the people who could potentially create these tools see it not only as not valuable, but actually counterproductive. Rather, they want to push Clojure's users to move from the Phill Model to the Rich Model, seeing that as a core benefit of this opinionated language and the philosophy behind it.