= Notes on the life and character of Eisenhower Part 1: World War 2

== Phase 1: To the end of WWI - innovation, friendships

The early career narrative of Eisenhower is one of rapid advancement without spectacular events. He was always impressed, but at this phase in his career did not uniformly recieve 'Superior' ratings like he would in the next phase.

His early relationship with Patton was notable, and he was notable in his early interest in tank warfare and its opportunities - though not the same extent Patton was.

He was notable in his personal relations for always getting along with people. His fiery temper is not often on full display as it would be later.

He was for the most part in junior but responsible positions.

== Phase 2: To the start of WWII - Pershing, Conner, MacArthur, luck

After the end of WWI he was tapped early to write the official American history of the war, working closely with Pershing in this capacity. Pershing was most complimentary about his dilligence and thouroughness in the endevour, which often took place under tight deadlines.

His prose writing was good, though not superlative like Grant's. It was notable for its clarity. From around this time Eisenhower starts to get almost exlusively 'Superior' results on the efficiency reports submitted by his commanders.

At around this time the most critical relationship of his early career was made, with Major General Fox Connor. Eisenhower was with Conner for a while, including in Panama, and Connor took him under his wing and gave him a 'second education' in the classics and in military history. Connor was influential with the high administrative functions of the Armed Forces, and would intervene at several key points in Eisenhower's career to get him plum assignments.

Eishenhower next went to the Philippines to work under MacArthur. At this time the US was loosening its grip on the former colony. MacArthur was not yet at this time the almost crazed figure that he later became, though he was certainly quirky. Eisenhower also developed a close relationhip with the first president of the Philippines, who frequently sought his opinion.

Over time MacArthur began to display the traits that would typify him in later years. He was impulsive, refused to listen to others, and wildly flamboyant in his language. He would rage when others disagreed with him. Eisenhower extracted himself from the situation when he had had enough, and when MacArthur had had enough of him - though he managed to avoid the perception that there had been any break, the first time that his political nous was on full display.

After MacArthur, Eisenhower held several posts, all prestigious, and excelled at all. He went to several command preparation academies, and worked in the office of the Army Chief of Staff. He continued to develop and maintain excellent relationships with important people, including at this time Marshall.

== Phase 3: WW2 before OVERLORD - Marshall, TORCH, GYMNAST and Lessons in theatre command

Eisenhower was chosen as the commander of the TORCH operation, despite having no experience of commanding troops or being in a war. The intention was that he would also prepare the way for OVERLORD, which was earmarked for command by Marshall (or Brooke).

The early American efforts in North Africa were quite comically bad. The strategy was flawed (the landings were much too far West), and the political situation with the Vichy government was mishandled. Eisenhower did not, objectively, do a great job as commander of TORCH. But his superiors either cut him a lot of slack, or were carefully managed by Ike.

However, he learned a great deal very quickly from the experience. He started displaying great executive ability, able to effectively delegate and keep his contributions at the right level. After a disasterous strategy briefing with the more experienced British commanders, where his 'classroom excercise' level plans were torn to pieces, he largely left the preparation of planning offensives to subordinates who were good at that sort of thing - Monty for the Normandy invasions for example. Many, many people commented throughout the war that his strategic planning ability and battlefield sense was just awful, rooted in the antiquated American doctrine of frontal assault on a wide front, when better battlefield commanders like Patton and Bradley had moved on.

Throughout he displayed consumate political skill in handling coalition partners. In this area there have been few better in all of history. This was particularly difficult when you consider that many Americans and French hated the British, and that the Americans and British (not to mention the French themselves) were split between support for De Gaulle's Free French and conciliation of the Vichy Regime. FDR in particular hated De Gaulle, and the Americans in general were explicitly in favor of trying to 'turn' Vichy officials. He absolutely charmed the pants of everyone. Every quote from those he worked closely with is drenched with praise. It says much that the famously difficult and aloof De Gaulle loved Eisenhower, and disliked or was disdainful of almost everyone else.

After the troubles in North Africa, the Sicily invasion was better planning and executed, with Eisenhower largely out of the planning, and the planners learning the lessons from TORCH (the blot on the copy book was letting several excellent German divisions escape unmolested across the straights of Messina). The Italy invasion went less well. The expectation was that the Italians were ready to fold, and resistance would be light. Instead, Germany under Model resisted fiercly and in strength. Eisenhower made quick corrections, but the Italian campaign was never especially successful, and Eisenhower displayed the other skill he had in abundance: the subtle fudging of the record to make things appear better than they were. In this case a lot of the blame was shifted to Montgomery, when in fact the fault was in the planning.

Marshall, during this entire time and going foward, was a dream superior. His confidence in Ike never waivered. He was supportive of Eisenhower's decisions, but never got directly involved or micromanaged.

== Phase 4: OVERLORD - Executive mastery, Churchill FDR and De Gaulle

Eisenhower was moved over to act as supreme commander of the Channel Crossing. Learning his lessons, he put Montgomery in charge of planning the invasion, and also had him command the ground forces in the field. Monty was very good at this stuff, and Ike let him get on with it.

Eisenhower's responsibilities at this stage were mainly conciliating personalities, and convincing various people to hand over authority to him. On the latter, he managed to get the Strategic Bomber commands of both UK and US under his umbrella, despite great resistance from their respective commanders. Much of his effort was spent persuading Churchill, who was still less than enthusiatic about invading France from either north or south, and preferred a focus on Italy, and trying to prepare for the post-invasion administration of France.

This last was made infinitely more difficult by FDRs resistance. Ike was convinced by this point that De Gaulle was the only one who could really manage a post-German France. The alternative, favored by the President, was that Vichy officials would remain in key positions, with a de facto occupation by UK and American forces. Not only did Eisenhower not believe this would work politically, but he didn't want to have to assume the burden of himself managing France. Through very fancy footwork indeed, Eisenhower managed to make it clear to De Gaulle that he expected him to take over in France, and would assist him in it, but also managed to keep FDR to a large degree onside.

Though by now supremely effective at delegating, Eisenhower made the big decisions when he needed to, and was careful to emphasis that the responsibility for the consequences were on him alone (though when things went badly he was phenomenally good at shaping the narrative in his favor). The two main examples are the airbourne drops on the Cherbourg Peninsula, and the Go decision for Overlord. In the first, one of his generals came to him with concerns that the two airbourne divisions that were due to support the Utah and Omaha landings would get torn to pieces by anti-aircraft fire and air cover. Eisenhower told him to put his concerns in writing, then after thinking about for a while he decided to go ahead with the drops and confirmed the same to the general, also in writing. The basis for his decision seems to have been based on his similar experience in Italy, where paratroopers got through OK. In the event they did in Normandy too.