= Blog Build

This blog was from the start set up to use Github Pages to display html files.

The first posts I wrote here were written in Org mode, and then converted to html, I forget how exactly but presumably using something in Emacs.

Next I moved to ASCIIDOCs, and converted to HTML from the command line with asciidoctor.

I introduced some automation through a very simple babashka script `pub.clj` which did the asciidoctor conversion then moved the resulting html file to the appropriate folder.

[source,clojure]
----
#!/usr/bin/env bb
(require '[clojure.java.shell :refer [sh]]
         '[clojure.string :refer [replace]])

(let [[type path] *command-line-args*]
  (doall [(sh "asciidoctor" path)
          (sh "mv" (replace path ".adoc" ".html") 
                   (str "../" type))]))
----

Which was executed like `./pub.clj posts my_post_name.adoc`

I still have to manually update the index.html with an entry like this

[source,html]
----
<tr>
  <td>2000-01-01</td>
  <td><a href="./posts/test.adoc">Test</a></td>
</tr>
----

I want to take the automation a few steps further.

== Goals

* When I write a new (adoc) post, I want the post to be converted to html automatically
* When I write a new post, I want the index to be updated with an entry and link to that post
* When I update an existing post, I want the html to be updated
* I want the above to happen when I push a commit of posts to the github repo

== Persistent state?

THe first thing to note is that I either:

* re-convert every adoc and fully rebuild the index on every run
* store the state of the previous run to detect new adocs and updated adocs.

I wonder how fast it would be to convert every post? Let's run a test.

I have about 100 posts so far. I tried converting all of them in one go using the following script

[source,clojure]
----
(defn convert [path filename]
  (sh "asciidoctor" (str path filename)))

(time (mapv #(convert "../asciidocs/posts/" %)
            (str/split-lines (:out (sh "ls" "../asciidocs/posts")))))
----

This took around 10 seconds, which I think is OK for a first pass. 300 posts would take around 30 seconds, and 600 a minute, which is probably where I would put the line for 'too long'. Obviously I'm a long way from there.

So let's go with that for now: no state, just reconvert everything.

== Blocking out work

* Build the index from the posts
* convert all files from adoc to html and move them to the proper path.
* Automating the conversion using Github actions

== Converting adocs

This isn't so different from the script I scratched out above:

== Creating the index

This seems a little 

For the first I'll use hiccup templating
